//! Palette pack resource loading
//!
//! Discovery differs by platform, deliberately:
//! - **Desktop** scans `assets/palettes/packs` at startup — the folder
//!   is the catalog, and what ships in the repo is the default set.
//! - **WASM** cannot list a directory, so it embeds a manifest that
//!   `build.rs` generates from that same folder at compile time, and
//!   lazily fetches pack content on demand. Nothing is committed, so
//!   the manifest cannot drift from the folder.

use super::{fetch_json, FetchError, LoadState, PackMetadata, ResourceManifest};
use crate::scene::palette::PalettePack;

/// The pack embedded in the binary as the offline fallback.
///
/// One literal, because three things have to name the same file: what
/// gets embedded, which file the desktop folder scan skips, and which
/// manifest entry WASM skips — both skips exist because the pack is
/// already loaded from the embedded copy. When these drifted apart
/// (the embedded pack moved from `builtin.json` to `starter_pack.json`
/// while the skips still said "builtin") the pack loaded twice on
/// desktop AND on web. `concat!` expands this macro, so the include
/// path and the constant cannot disagree.
macro_rules! builtin_pack_file {
    () => {
        "starter_pack.json"
    };
}

/// Filename of the embedded pack, for the discovery skips.
pub const BUILTIN_PACK_FILE: &str = builtin_pack_file!();

/// Built-in pack (embedded at compile time for offline fallback)
pub const BUILTIN_PACK_JSON: &str =
    include_str!(concat!("../../assets/palettes/packs/", builtin_pack_file!()));

/// Manifest for WASM pack discovery — generated by build.rs from the
/// packs folder. Compiled on every platform (desktop never reads it at
/// runtime) so the desktop test suite can validate what WASM will see.
pub const MANIFEST_JSON: &str = include_str!(concat!(env!("OUT_DIR"), "/palette_manifest.json"));

/// A palette pack with load state tracking
#[derive(Clone)]
pub struct PalettePackInfo {
    /// Metadata from manifest (id, name, description, file path)
    pub metadata: Option<PackMetadata>,
    /// Pack content (loaded from JSON)
    pub pack: Option<PalettePack>,
    /// Current load state
    pub load_state: LoadState,
    /// Whether this pack is enabled (included in palette list)
    pub enabled: bool,
    /// Whether this is the embedded built-in pack
    pub is_builtin: bool,
}

impl PalettePackInfo {
    /// Create a new pack info from manifest metadata
    pub fn from_metadata(metadata: PackMetadata) -> Self {
        Self {
            enabled: metadata.enabled_by_default,
            metadata: Some(metadata),
            pack: None,
            load_state: LoadState::NotLoaded,
            is_builtin: false,
        }
    }

    /// Create from a directly loaded pack (not via manifest)
    pub fn from_pack(pack: PalettePack, is_builtin: bool) -> Self {
        Self {
            enabled: pack.enabled_by_default,
            metadata: None,
            pack: Some(pack),
            load_state: LoadState::Loaded,
            is_builtin,
        }
    }

    /// Get pack name (from pack if loaded, otherwise from metadata)
    pub fn name(&self) -> &str {
        if let Some(pack) = &self.pack {
            &pack.pack_name
        } else if let Some(metadata) = &self.metadata {
            &metadata.name
        } else {
            "Unknown"
        }
    }

    /// Get pack description
    pub fn description(&self) -> &str {
        if let Some(pack) = &self.pack {
            &pack.description
        } else if let Some(metadata) = &self.metadata {
            &metadata.description
        } else {
            ""
        }
    }

    /// Get palette count (from pack if loaded, otherwise from metadata)
    pub fn palette_count(&self) -> usize {
        if let Some(pack) = &self.pack {
            pack.palettes.len()
        } else if let Some(metadata) = &self.metadata {
            metadata.item_count
        } else {
            0
        }
    }

    /// Check if pack is loaded
    pub fn is_loaded(&self) -> bool {
        matches!(self.load_state, LoadState::Loaded)
    }

    /// Check if pack is currently loading
    pub fn is_loading(&self) -> bool {
        matches!(self.load_state, LoadState::Loading)
    }

    /// Check if loading failed
    pub fn is_failed(&self) -> bool {
        matches!(self.load_state, LoadState::Failed(_))
    }

    /// Get error message if failed
    pub fn error_message(&self) -> Option<&str> {
        match &self.load_state {
            LoadState::Failed(msg) => Some(msg),
            _ => None,
        }
    }
}

/// Load the embedded built-in pack
pub fn load_builtin_pack() -> Result<PalettePack, FetchError> {
    serde_json::from_str(BUILTIN_PACK_JSON).map_err(FetchError::from)
}

/// Load the embedded manifest (for WASM - synchronous from compile-time embedded string)
pub fn load_embedded_manifest() -> Result<ResourceManifest, FetchError> {
    serde_json::from_str(MANIFEST_JSON).map_err(FetchError::from)
}

/// Load a palette pack from its file path (desktop - synchronous)
#[cfg(not(target_arch = "wasm32"))]
pub fn load_pack(file_path: &str) -> Result<PalettePack, FetchError> {
    // Construct full path relative to assets
    let full_path = format!("assets/palettes/packs/{}", file_path);
    fetch_json(&full_path)
}

/// Load a palette pack from its file path (WASM - async)
#[cfg(target_arch = "wasm32")]
pub async fn load_pack(file_path: &str) -> Result<PalettePack, FetchError> {
    // Construct full path relative to page
    let full_path = format!("assets/palettes/packs/{}", file_path);
    fetch_json(&full_path).await
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The generated manifest is what WASM sees; the folder is what
    /// desktop sees. This is the only place the two are compared, and
    /// it also catches what build.rs deliberately does not fail on: a
    /// pack JSON that no longer parses.
    #[test]
    fn generated_manifest_matches_packs_folder() {
        let manifest = load_embedded_manifest().expect("generated manifest must parse");

        let packs_dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("assets/palettes/packs");
        let mut on_disk: Vec<String> = std::fs::read_dir(&packs_dir)
            .expect("packs folder exists")
            .flatten()
            .filter_map(|e| e.file_name().to_str().map(String::from))
            .filter(|n| n.ends_with(".json") && n != "manifest.json")
            .collect();
        on_disk.sort();

        let mut in_manifest: Vec<String> =
            manifest.packs.iter().map(|p| p.file.clone()).collect();
        in_manifest.sort();

        assert_eq!(
            on_disk, in_manifest,
            "the packs folder and the generated manifest disagree — \
             a pack failed to parse in build.rs (see its warnings), or \
             build.rs's scan drifted from this test's"
        );

        for meta in &manifest.packs {
            let pack: PalettePack = serde_json::from_str(
                &std::fs::read_to_string(packs_dir.join(&meta.file)).unwrap(),
            )
            .unwrap_or_else(|e| panic!("{} does not parse as a PalettePack: {e}", meta.file));
            assert_eq!(meta.item_count, pack.palettes.len(), "{}: stale item_count", meta.file);
            assert_eq!(
                meta.enabled_by_default, pack.enabled_by_default,
                "{}: enabled_by_default disagrees between manifest and pack — \
                 the serde default and build.rs's default are out of step",
                meta.file
            );
            assert_eq!(meta.name, pack.pack_name, "{}: stale name", meta.file);
        }
    }
}
