/// Response from the UI layer indicating what actions should be taken
pub struct UiResponse {
    pub reset_requested: bool,
    pub flame_changed: bool,
    pub iterations_changed: bool,
    pub view_changed: bool,
    pub density_changed: bool,
    pub palette_changed: bool,
    pub color_mode_changed: bool,
    pub pause_changed: bool,
    pub config_export_requested: Option<String>,
    pub config_import_requested: Option<String>,
    pub config_save_file_requested: bool,
    pub config_load_file_requested: bool,
    pub custom_palette: Option<crate::scene::palette::Palette>,
    pub undo_requested: bool,
    pub redo_requested: bool,
    pub background_color_changed: bool,
    pub png_export_with_background: bool,
    pub png_export_transparent: bool,
    pub palette_export_json: Option<crate::scene::palette::Palette>,
    pub palette_save_file: Option<crate::scene::palette::Palette>,
    pub palette_import_json: Option<String>,
    pub palette_load_file: bool,
    pub palette_imported: Option<crate::scene::palette::Palette>,
    pub preset_changed: bool,
    pub add_transform: bool,
    pub delete_transform: Option<usize>, // Index of transform to delete
    pub render_mode_changed: bool,
    pub projection_changed: bool,
    pub camera_rotation_changed: bool,
}

impl Default for UiResponse {
    fn default() -> Self {
        Self {
            reset_requested: false,
            flame_changed: false,
            iterations_changed: false,
            view_changed: false,
            density_changed: false,
            palette_changed: false,
            color_mode_changed: false,
            pause_changed: false,
            config_export_requested: None,
            config_import_requested: None,
            config_save_file_requested: false,
            config_load_file_requested: false,
            custom_palette: None,
            undo_requested: false,
            redo_requested: false,
            background_color_changed: false,
            png_export_with_background: false,
            png_export_transparent: false,
            palette_export_json: None,
            palette_save_file: None,
            palette_import_json: None,
            palette_load_file: false,
            palette_imported: None,
            preset_changed: false,
            add_transform: false,
            delete_transform: None,
            render_mode_changed: false,
            projection_changed: false,
            camera_rotation_changed: false,
        }
    }
}
