//! Simulation textures (`docs/projects/sim-textures.md`).
//!
//! A texture is not an image file. It is a **Simulation-mode config**: a
//! small recipe, `(model, params, seed, init, steps)` with its colouring
//! and palette, that reproduces its field exactly. That is what makes it
//! portable where image files were not: the recipe lives in the config
//! that uses it (`EscapeConfig::texture`, embedded in full), so the
//! picture needs nothing else -- no path to break, nothing to upload.
//!
//! The library lists the textures a user can pick: shipped presets
//! (`assets/textures/*.fflame`, embedded in the binary by `build.rs`)
//! and the user's own, saved from Simulation mode (`textures/` in the
//! storage backend: the data directory, or browser storage). The image a
//! recipe generates is derived data, cached as a PNG ([`cache`]) and
//! regenerated whenever the cache does not have it.

pub mod cache;

use crate::config::sim::SimGrid;
use crate::config::FractalConfig;
use crate::scene::transforms::RenderMode;

/// The largest texture side: a 2048² RGBA8 texture is 16 MB.
pub const MAX_TEXTURE_SIDE: u32 = 2048;

/// The storage-backend folder user textures live in.
const USER_DIR: &str = "textures";
const EXT: &str = "fflame";

// `TEXTURE_PRESETS: &[(&str, &str)]`, (name, file contents), one per
// `assets/textures/*.fflame`, generated by build.rs.
include!(concat!(env!("OUT_DIR"), "/texture_presets.rs"));

/// Bumped whenever a user texture is saved, renamed or deleted, so a
/// panel showing the library knows to read it again.
static LIBRARY_GENERATION: std::sync::atomic::AtomicU64 = std::sync::atomic::AtomicU64::new(0);

pub fn library_generation() -> u64 {
    LIBRARY_GENERATION.load(std::sync::atomic::Ordering::Relaxed)
}

fn library_changed() {
    LIBRARY_GENERATION.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
}

/// Where a library entry came from.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TextureOrigin {
    /// Shipped with the app.
    Preset,
    /// Saved by the user from Simulation mode.
    User,
}

/// One texture the panel offers.
#[derive(Debug, Clone)]
pub struct TextureEntry {
    pub name: String,
    pub origin: TextureOrigin,
    pub config: FractalConfig,
}

/// The textures a user can pick: presets first, then their own.
#[derive(Debug, Clone, Default)]
pub struct TextureLibrary {
    pub entries: Vec<TextureEntry>,
}

impl TextureLibrary {
    /// Every preset and every user texture. A file that does not parse is
    /// left out with a warning rather than failing the list.
    pub fn load() -> Self {
        let mut entries = Vec::new();
        for (name, json) in TEXTURE_PRESETS {
            match FractalConfig::from_json(json) {
                Ok(config) => entries.push(TextureEntry { name: name.to_string(), origin: TextureOrigin::Preset, config }),
                Err(e) => log::warn!("texture preset {name} does not parse: {e}"),
            }
        }
        let mut users: Vec<TextureEntry> = crate::storage::backend::list_entries(std::path::Path::new(USER_DIR))
            .unwrap_or_default()
            .into_iter()
            .filter_map(|file| {
                let name = file.strip_suffix(&format!(".{EXT}"))?.to_string();
                let json = crate::storage::backend::read_file(&user_path(&name)).ok()?;
                match FractalConfig::from_json(&json) {
                    Ok(config) => Some(TextureEntry { name, origin: TextureOrigin::User, config }),
                    Err(e) => {
                        log::warn!("user texture {name} does not parse: {e}");
                        None
                    }
                }
            })
            .collect();
        users.sort_by_key(|e| e.name.to_lowercase());
        entries.extend(users);
        Self { entries }
    }

    pub fn find(&self, name: &str) -> Option<&TextureEntry> {
        self.entries.iter().find(|e| e.name == name)
    }
}

/// A name a user texture can be stored under: letters, digits, spaces,
/// `-` and `_`, trimmed; never empty.
pub fn sanitize_name(name: &str) -> String {
    let clean: String = name
        .chars()
        .filter(|c| c.is_alphanumeric() || matches!(c, ' ' | '-' | '_'))
        .collect::<String>()
        .trim()
        .to_string();
    if clean.is_empty() {
        "Texture".to_string()
    } else {
        clean.chars().take(64).collect()
    }
}

fn user_path(name: &str) -> std::path::PathBuf {
    std::path::Path::new(USER_DIR).join(format!("{name}.{EXT}"))
}

/// Save a Simulation-mode config as a user texture. `viewport` is the
/// output size the simulation is shown at, which a viewport-scaled grid
/// is fixed from (see [`as_recipe`]). Returns the name it was stored
/// under: the sanitised name, numbered if a texture already has it.
pub fn save_user(name: &str, config: &FractalConfig, viewport: (u32, u32)) -> anyhow::Result<String> {
    let base = sanitize_name(name);
    let taken: Vec<String> = TextureLibrary::load().entries.into_iter().map(|e| e.name).collect();
    let mut stored = base.clone();
    let mut n = 2;
    while taken.iter().any(|t| t.eq_ignore_ascii_case(&stored)) {
        stored = format!("{base} {n}");
        n += 1;
    }
    let json = as_recipe(config, viewport).to_json()?;
    crate::storage::backend::write_file(&user_path(&stored), &json).map_err(|e| anyhow::anyhow!("{e:?}"))?;
    library_changed();
    Ok(stored)
}

/// Delete a user texture.
pub fn delete_user(name: &str) -> anyhow::Result<()> {
    crate::storage::backend::delete_file(&user_path(name)).map_err(|e| anyhow::anyhow!("{e:?}"))?;
    library_changed();
    Ok(())
}

/// Rename a user texture. Returns the name it ended up under.
pub fn rename_user(old: &str, new: &str) -> anyhow::Result<String> {
    let json = crate::storage::backend::read_file(&user_path(old)).map_err(|e| anyhow::anyhow!("{e:?}"))?;
    let config = FractalConfig::from_json(&json)?;
    let size = texture_size(&config);
    let stored = save_user(new, &config, size)?;
    delete_user(old)?;
    Ok(stored)
}

/// A Simulation-mode config made into a texture recipe:
/// - a viewport-scaled grid becomes a fixed one, at the size it has at
///   `viewport`, so the texture's size belongs to the recipe;
/// - the grid is capped at [`MAX_TEXTURE_SIDE`] on its longer side;
/// - letterboxed, so at its own size the grid fills the image edge to
///   edge and a periodic run tiles;
/// - any texture of its own is dropped: textures do not nest.
pub fn as_recipe(config: &FractalConfig, viewport: (u32, u32)) -> FractalConfig {
    let mut recipe = config.clone();
    recipe.render_mode = RenderMode::Simulation;
    let (mut w, mut h) = recipe.sim.grid.cells_for(viewport.0.max(1), viewport.1.max(1));
    let longer = w.max(h);
    if longer > MAX_TEXTURE_SIDE {
        let k = MAX_TEXTURE_SIDE as f64 / longer as f64;
        w = ((w as f64 * k).round() as u32).max(1);
        h = ((h as f64 * k).round() as u32).max(1);
    }
    recipe.sim.grid = SimGrid::Fixed { width: w, height: h };
    recipe.sim.fit = crate::config::sim::SimFit::Letterbox;
    recipe.escape.texture = None;
    recipe
}

/// The size a recipe generates at: its grid, as [`as_recipe`] fixed it
/// (a recipe that somehow kept a viewport grid is read at 512²).
pub fn texture_size(config: &FractalConfig) -> (u32, u32) {
    let (w, h) = config.sim.grid.cells_for(512, 512);
    (w.clamp(1, MAX_TEXTURE_SIDE), h.clamp(1, MAX_TEXTURE_SIDE))
}

/// Generate a recipe's texture: the recipe rendered through the headless
/// path at its own size -- exactly what Simulation mode draws, at the
/// step count the recipe names.
pub async fn generate(
    device: &egui_wgpu::wgpu::Device,
    queue: &egui_wgpu::wgpu::Queue,
    recipe: &FractalConfig,
) -> anyhow::Result<image::RgbaImage> {
    let (w, h) = texture_size(recipe);
    let job = crate::renderer::RenderJob::new(recipe, w, h);
    let out = crate::renderer::render(device, queue, job, &mut crate::renderer::NoProgress).await?;
    image::RgbaImage::from_raw(out.width, out.height, out.rgba_data)
        .ok_or_else(|| anyhow::anyhow!("texture render returned the wrong number of bytes"))
}

/// A recipe's texture: from the cache, or generated and cached.
pub async fn obtain(
    device: &egui_wgpu::wgpu::Device,
    queue: &egui_wgpu::wgpu::Queue,
    recipe: &FractalConfig,
) -> anyhow::Result<image::RgbaImage> {
    let key = cache::key(recipe);
    if let Some(image) = cache::load(&key) {
        return Ok(image);
    }
    let image = generate(device, queue, recipe).await?;
    cache::save(&key, &image);
    Ok(image)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_preset_parses_as_a_fixed_grid_simulation() {
        assert!(!TEXTURE_PRESETS.is_empty(), "no texture presets were embedded");
        for (name, json) in TEXTURE_PRESETS {
            let config = FractalConfig::from_json(json).unwrap_or_else(|e| panic!("{name}: {e}"));
            assert_eq!(config.render_mode, RenderMode::Simulation, "{name} is not a simulation");
            assert!(matches!(config.sim.grid, SimGrid::Fixed { .. }), "{name} does not fix its grid");
            assert!(config.escape.texture.is_none(), "{name} nests a texture");
            let (w, h) = texture_size(&config);
            assert!(w <= MAX_TEXTURE_SIDE && h <= MAX_TEXTURE_SIDE, "{name} is {w}x{h}");
        }
    }

    #[test]
    fn a_recipe_fixes_its_grid_caps_it_and_drops_nested_textures() {
        let mut config = FractalConfig::default();
        config.sim.grid = SimGrid::Viewport { scale: 2.0 };
        config.escape.texture = Some(crate::config::escape::EscapeTexture {
            name: "inner".to_string(),
            config: Box::new(FractalConfig::default()),
        });
        let recipe = as_recipe(&config, (1600, 900));
        assert_eq!(recipe.render_mode, RenderMode::Simulation);
        assert_eq!(recipe.sim.grid, SimGrid::Fixed { width: 2048, height: 1152 });
        assert!(recipe.escape.texture.is_none());
        assert_eq!(texture_size(&recipe), (2048, 1152));
    }

    /// The shipped textures, built from the simulation engine's own
    /// measured presets (`SimPreset`: parameters, steps, init, colouring),
    /// on a periodic 512² grid so they tile, through a grey ramp so they
    /// are neutral -- a bump map and an overlay both read them as they
    /// are. Writes `assets/textures/<name>.fflame`; run deliberately.
    #[test]
    #[ignore = "writes assets/textures"]
    #[cfg(feature = "engine-sim")]
    fn write_texture_presets() {
        let chosen: &[(&str, &str, &str)] = &[
            ("Mitosis", "gray_scott", "mitosis"),
            ("Coral", "gray_scott", "coral"),
            ("Maze", "gray_scott", "maze"),
            ("Worms", "gray_scott", "worms"),
        ];
        let dir = std::path::Path::new("assets/textures");
        std::fs::create_dir_all(dir).unwrap();
        for (name, model, preset) in chosen {
            let def = crate::sim::MODELS.iter().find(|m| m.name == *model).unwrap_or_else(|| panic!("{model}"));
            let pre = def.preset(preset).unwrap_or_else(|| panic!("{model}/{preset}"));
            let mut c = FractalConfig::default();
            c.render_mode = RenderMode::Simulation;
            c.tonemap_mode = crate::scene::tonemap::ToneMapMode::Linear;
            c.exposure = 1.0;
            c.gamma = 1.0;
            let stop = |position: f32, v: f32| crate::scene::palette::ColorStop { position, color: [v, v, v] };
            c.palette.name = "Grey ramp".to_string();
            c.palette.stops = vec![stop(0.0, 0.0), stop(1.0, 1.0)];
            c.sim.model = model.to_string();
            c.sim.model_params = pre.params.iter().map(|(k, v)| (k.to_string(), *v)).collect();
            c.sim.steps = pre.steps;
            c.sim.steps_per_frame = (pre.steps / 200).clamp(4, 2048);
            if !def.has(crate::sim::ModelFeature::NoTimeStep) {
                c.sim.dt = def.default_dt;
            }
            // Seeded everywhere, so the pattern develops over the whole
            // tile at once: the presets' six blobs were measured for the
            // viewport and leave most of a 512² grid empty at their step
            // count.
            c.sim.init = pre.init.unwrap_or(crate::config::sim::SimInit::Blobs { count: 64, radius: 10 });
            if let Some(col) = pre.coloring {
                c.sim.coloring = col.to_string();
                c.sim.coloring_params = pre.coloring_params.iter().map(|(k, v)| (k.to_string(), *v)).collect();
            }
            c.sim.matte = pre.matte.unwrap_or_default();
            c.sim.warp = pre.warp.unwrap_or_default();
            c.sim.boundary = crate::config::sim::SimBoundary::Periodic;
            c.sim.grid = SimGrid::Fixed { width: 512, height: 512 };
            c.sim.fit = crate::config::sim::SimFit::Letterbox;
            let path = dir.join(format!("{name}.{EXT}"));
            std::fs::write(&path, c.to_json().unwrap() + "\n").unwrap();
            println!("wrote {}", path.display());
        }
    }

    /// Generation is the recipe and nothing else: two runs give the same
    /// bytes, and a periodic texture tiles -- its opposite edges continue
    /// into each other about as smoothly as its inside does.
    #[test]
    #[ignore = "needs a GPU"]
    #[cfg(feature = "engine-sim")]
    fn textures_generate_deterministically_and_tile() {
        use egui_wgpu::wgpu;
        // The adapter's own limits, as every renderer test asks for: the
        // defaults are below what the render path binds.
        let instance = wgpu::Instance::new(wgpu::InstanceDescriptor {
            backends: wgpu::Backends::all(),
            ..wgpu::InstanceDescriptor::new_without_display_handle()
        });
        let adapter = pollster::block_on(instance.request_adapter(&wgpu::RequestAdapterOptions {
            power_preference: wgpu::PowerPreference::HighPerformance,
            force_fallback_adapter: false,
            compatible_surface: None,
        }))
        .expect("adapter");
        let (device, queue) = pollster::block_on(adapter.request_device(&wgpu::DeviceDescriptor {
            label: Some("texture test"),
            // What the app's device has: the render path clears textures.
            required_features: wgpu::Features::CLEAR_TEXTURE,
            required_limits: adapter.limits(),
            memory_hints: wgpu::MemoryHints::Performance,
            experimental_features: Default::default(),
            trace: Default::default(),
        }))
        .expect("device");
        for (name, json) in TEXTURE_PRESETS {
            let recipe = FractalConfig::from_json(json).unwrap();
            let t0 = std::time::Instant::now();
            let a = pollster::block_on(generate(&device, &queue, &recipe)).expect("generate");
            let secs = t0.elapsed().as_secs_f64();
            let b = pollster::block_on(generate(&device, &queue, &recipe)).expect("generate");
            assert_eq!((a.width(), a.height()), texture_size(&recipe), "{name}: size");
            assert!(a.as_raw() == b.as_raw(), "{name}: two runs differ");
            // Mean step across the seam against the mean step inside.
            let lum = |x: u32, y: u32| a.get_pixel(x, y)[0] as f64;
            let (w, h) = (a.width(), a.height());
            let (mut seam, mut inside) = (0.0, 0.0);
            for y in 0..h {
                seam += (lum(w - 1, y) - lum(0, y)).abs();
                inside += (lum(w / 2, y) - lum(w / 2 - 1, y)).abs();
            }
            for x in 0..w {
                seam += (lum(x, h - 1) - lum(x, 0)).abs();
                inside += (lum(x, h / 2) - lum(x, h / 2 - 1)).abs();
            }
            let spread = {
                let v: Vec<u8> = a.pixels().map(|p| p[0]).collect();
                (*v.iter().max().unwrap() as i32 - *v.iter().min().unwrap() as i32) as f64
            };
            println!("{name}: {}x{} in {secs:.2} s, seam step {:.2} vs inside {:.2}, spread {spread}", w, h, seam / (w + h) as f64, inside / (w + h) as f64);
            assert!(spread > 64.0, "{name}: the texture is nearly flat");
            assert!(seam <= inside * 1.5 + 1.0, "{name}: the edges do not continue into each other");
        }
    }

    #[test]
    fn names_are_sanitised() {
        // Path characters go, and nothing is put in their place.
        assert_eq!(sanitize_name("  Coral/../reef: v2 "), "Coralreef v2");
        assert_eq!(sanitize_name("///"), "Texture");
    }

    /// The recipe rides inside the config that uses it, in its file form,
    /// and comes back the same.
    #[test]
    fn an_embedded_recipe_round_trips_through_the_parent_file() {
        let (name, json) = TEXTURE_PRESETS[0];
        let recipe = FractalConfig::from_json(json).unwrap();
        let mut parent = FractalConfig::default();
        parent.render_mode = RenderMode::Escape;
        parent.escape.texture = Some(crate::config::escape::EscapeTexture {
            name: name.to_string(),
            config: Box::new(recipe),
        });
        let text = parent.to_json().unwrap();
        let back = FractalConfig::from_json(&text).unwrap();
        assert_eq!(back.escape.texture, parent.escape.texture);
        assert_eq!(cache::key(&back.escape.texture.unwrap().config), cache::key(&parent.escape.texture.unwrap().config));
    }
}
