//! harmonograph_js (Jesus Sosa)
//!
//! Damped-pendulum harmonograph: emits points on a Lissajous-like curve
//! generated by 4 damped sinusoids (2 per axis) sampled at random
//! `t ∈ [0, time]`.
//!
//!   x = (mo_x(t) / 180), y = (mo_y(t) / 180)
//!   mo(t, a1, f1, p1, d1, a2, f2, p2, d2) =
//!       a1·sin(t·f1 + p1·π/180)·exp(-d1·t)
//!     + a2·sin(t·f2 + p2·π/180)·exp(-d2·t)
//!
//! 18 user params (seed/time + 4 oscillator-tuples × {a, f, p, d}). The
//! `seed` field is unused in our port — cpp re-seeds GOODRAND on each
//! Prepare; we use the per-thread rng instead. `time` is the max value
//! of the random `t`.
//!
//! Note: the cpp port has a bug — its `mo()` helper references `VAR(a1)`
//! / `VAR(f1)` etc. (globals) instead of its local args. The Java
//! original (embedded in the file as comments) uses local args
//! correctly. We follow Java semantics.
//!
//! Source: `output/jwildfire-vars/output/harmonograph_js.cpp` (Java
//! reference at line 252).

use crate::variations::{
    definition::{VariationDef, VariationParamDef},
    ParamType, VariationCategory, VariationPhase,
};
use crate::param;

pub static HARMONOGRAPH_JS: VariationDef = VariationDef {
    name: "harmonograph_js",
    display_name: "Harmonograph (Sosa)",
    category: VariationCategory::Advanced2D,
    phase: VariationPhase::Normal,
    needs_rng: true,
    parameters: &[
        param!("seed", "Seed", int, 1234.0, 0.0, 999999.0),
        param!("time", "Time", int, 100.0, 1.0, 1000.0),
        param!("a1", "A1", int, 0.0, 0.0, 360.0),
        param!("f1", "F1", unlimited_float, 0.0, -10.0, 10.0),
        param!("p1", "P1", int, 0.0, 0.0, 360.0),
        param!("d1", "D1", unlimited_float, 0.0, 0.0, 1.0),
        param!("a2", "A2", int, 0.0, 0.0, 360.0),
        param!("f2", "F2", unlimited_float, 0.0, -10.0, 10.0),
        param!("p2", "P2", int, 0.0, 0.0, 360.0),
        param!("d2", "D2", unlimited_float, 0.0, 0.0, 1.0),
        param!("a3", "A3", int, 0.0, 0.0, 360.0),
        param!("f3", "F3", unlimited_float, 0.0, -10.0, 10.0),
        param!("p3", "P3", int, 0.0, 0.0, 360.0),
        param!("d3", "D3", unlimited_float, 0.0, 0.0, 1.0),
        param!("a4", "A4", int, 0.0, 0.0, 360.0),
        param!("f4", "F4", unlimited_float, 0.0, -10.0, 10.0),
        param!("p4", "P4", int, 0.0, 0.0, 360.0),
        param!("d4", "D4", unlimited_float, 0.0, 0.0, 1.0),
    ],
    needs_transform: false,
    writes_color: false,
    init_param_count: 0,
    wgsl_init: None,
    state_count: 0,
    wgsl_state_init: None,
    needs_accum: false,
    wgsl_2d: r#"
fn mo_harmonograph(t: f32, a1: f32, f1: f32, p1deg: f32, d1: f32, a2: f32, f2: f32, p2deg: f32, d2: f32) -> f32 {
    let pi = 3.14159265358979;
    let p1 = p1deg * pi / 180.0;
    let p2 = p2deg * pi / 180.0;
    return a1 * sin(t * f1 + p1) * exp(-d1 * t) + a2 * sin(t * f2 + p2) * exp(-d2 * t);
}

fn variation_harmonograph_js(p: vec2<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec2<f32> {
    let time = get_param(xform_id, variation_id, 1u);
    let a1 = get_param(xform_id, variation_id, 2u);
    let f1 = get_param(xform_id, variation_id, 3u);
    let p1 = get_param(xform_id, variation_id, 4u);
    let d1 = get_param(xform_id, variation_id, 5u);
    let a2 = get_param(xform_id, variation_id, 6u);
    let f2 = get_param(xform_id, variation_id, 7u);
    let p2 = get_param(xform_id, variation_id, 8u);
    let d2 = get_param(xform_id, variation_id, 9u);
    let a3 = get_param(xform_id, variation_id, 10u);
    let f3 = get_param(xform_id, variation_id, 11u);
    let p3 = get_param(xform_id, variation_id, 12u);
    let d3 = get_param(xform_id, variation_id, 13u);
    let a4 = get_param(xform_id, variation_id, 14u);
    let f4 = get_param(xform_id, variation_id, 15u);
    let p4 = get_param(xform_id, variation_id, 16u);
    let d4 = get_param(xform_id, variation_id, 17u);

    let t = rng_nextf(rng) * time;
    let x = mo_harmonograph(t, a1, f1, p1, d1, a2, f2, p2, d2) / 180.0;
    let y = mo_harmonograph(t, a3, f3, p3 + 90.0, d3, a4, f4, p4 + 90.0, d4) / 180.0;
    return vec2<f32>(x, y);
}
"#,
    wgsl_3d: Some(r#"
fn mo_harmonograph(t: f32, a1: f32, f1: f32, p1deg: f32, d1: f32, a2: f32, f2: f32, p2deg: f32, d2: f32) -> f32 {
    let pi = 3.14159265358979;
    let p1 = p1deg * pi / 180.0;
    let p2 = p2deg * pi / 180.0;
    return a1 * sin(t * f1 + p1) * exp(-d1 * t) + a2 * sin(t * f2 + p2) * exp(-d2 * t);
}

fn variation_harmonograph_js(p: vec3<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec3<f32> {
    let time = get_param(xform_id, variation_id, 1u);
    let a1 = get_param(xform_id, variation_id, 2u);
    let f1 = get_param(xform_id, variation_id, 3u);
    let p1 = get_param(xform_id, variation_id, 4u);
    let d1 = get_param(xform_id, variation_id, 5u);
    let a2 = get_param(xform_id, variation_id, 6u);
    let f2 = get_param(xform_id, variation_id, 7u);
    let p2 = get_param(xform_id, variation_id, 8u);
    let d2 = get_param(xform_id, variation_id, 9u);
    let a3 = get_param(xform_id, variation_id, 10u);
    let f3 = get_param(xform_id, variation_id, 11u);
    let p3 = get_param(xform_id, variation_id, 12u);
    let d3 = get_param(xform_id, variation_id, 13u);
    let a4 = get_param(xform_id, variation_id, 14u);
    let f4 = get_param(xform_id, variation_id, 15u);
    let p4 = get_param(xform_id, variation_id, 16u);
    let d4 = get_param(xform_id, variation_id, 17u);

    let t = rng_nextf(rng) * time;
    let x = mo_harmonograph(t, a1, f1, p1, d1, a2, f2, p2, d2) / 180.0;
    let y = mo_harmonograph(t, a3, f3, p3 + 90.0, d3, a4, f4, p4 + 90.0, d4) / 180.0;
    return vec3<f32>(x, y, p.z);
}
"#),
};
