//! `hecke_group` — Hecke group H(q) orbit chaos game (modular group at
//! q = 3).
//!
//! The Hecke group H(q) is the Fuchsian group generated by
//!
//! ```text
//! S = [[0, −1], [1, 0]]        (inversion z ↦ −1/z, elliptic order 2)
//! T = [[1, λ], [0, 1]]         (translation z ↦ z + λ),  λ = 2·cos(π/q)
//! ```
//!
//! q = 3 gives λ = 1: the **modular group PSL(2,ℤ)** — the Farey
//! tessellation / Ford-circle structure. The product ST is elliptic of
//! order q (tr = λ, verified numerically), which is what makes the
//! group discrete for integer q ≥ 3 (Hecke's theorem; λ ≥ 2 is also
//! discrete but of infinite covolume). The chaos game plots the random
//! orbit: S is an involution and T parabolic, so orbit points pile
//! along circle/horocycle families accumulating on the real line — the
//! Ford-circle fan. (Bagula's Fuchsian-triangle generator
//! `s1 = [[t,−1],[1,0]]` is exactly the Hecke-style element `T·S` with
//! the trace pushed past 2.)
//!
//! Generator set `{S, T, T⁻¹}` (S is its own inverse as a Möbius map,
//! so it appears once); `avoid_reversal` uses the involution-aware
//! pairing 0↔0, 1↔2.
//!
//! `space` = Hyperbolic H3: the Poincaré extension lifts the orbit into
//! upper half-space — the Ford spheres.
//!
//! Uses `Feature::NeedsMobiusLib` (`shaders/core/su_mobius.wgsl`).

use crate::variations::{
    definition::{Feature, VariationDef, VariationParamDef},
    ParamType, VariationCategory, VariationPhase,
};
use crate::param;

/// Hecke group H(q) orbit chaos game; q = 3 is the modular group
/// PSL(2,ℤ).
///
/// # Authors
/// - Fractals for All
/// - Claude Fable 5
pub static HECKE_GROUP: VariationDef = VariationDef {
    name: "hecke_group",
    aliases: &[],
    display_name: "Hecke Group",
    category: VariationCategory::Advanced2D,
    phase: VariationPhase::Normal,
    features: &[Feature::NeedsRng, Feature::WritesColor, Feature::NeedsMobiusLib, Feature::AlwaysZ],
    // Slot 0: previous generator index (avoid_reversal). Slot 1: color
    // register for the Generator color mode.
    state_count: 2,
    wgsl_state_init: None,
    parameters: &[
        param!("q", "Q", int, 3.0, 3.0, 24.0, "Hecke parameter: λ = 2·cos(π/q). q = 3 is the modular group PSL(2,ℤ) (Farey / Ford circles); larger q widens the translation toward the λ = 2 limit."),
        param!("avoid_reversal", "Avoid Reversal", bool, true, "Skip the inverse of the previous generator (T after T⁻¹ and vice versa; S is its own inverse and is never blocked). Off = all three generators equally likely."),
        param!("dc_mode", "Color Mode", enum, 0, &["Off", "Generator"], "Direct-color source (needs the transform's Direct Color > 0). Generator: S / T / T⁻¹ each have their own palette position, blended through a persistent color register at Color Speed."),
        param!("dc_scale", "Color Scale", float, 1.0, 0.1, 8.0, "Palette-index multiplier for the Generator color (wrapped with fract)."),
        param!("color_speed", "Color Speed", float, 0.5, 0.0, 1.0, "How hard each generator pulls the color register toward its own palette position."),
        param!("space", "Space", enum, 0, &["Planar", "Hyperbolic H3"], "3D render mode only. Planar: the Möbius orbit in the xy plane (z passes through). Hyperbolic H3: the Poincaré extension into upper half-space — the Ford-sphere fan. The t→0 slice is the 2D picture."),
        param!("symmetry", "Symmetry", enum, 0, &["None", "2-Fold Point", "2-Fold Mirror", "4-Fold"], "Random output symmetrization each call: 2-Fold Point = {z,−z}, 2-Fold Mirror = {z,conj z}, 4-Fold = both."),
    ],
    init_param_count: 0,
    wgsl_init: None,
    wgsl_2d: WGSL_2D,
    wgsl_3d: WGSL_3D,
};

// Generators: 0 = S (own inverse), 1 = T, 2 = T⁻¹. The reversal map is
// 0↔0, 1↔2 — S is never blocked.
const WGSL_2D: &str = r#"
fn hecke_gen(k: u32, lam: f32) -> SuMat {
    switch k {
        case 0u: { return SuMat(vec2<f32>(0.0, 0.0), vec2<f32>(-1.0, 0.0), vec2<f32>(1.0, 0.0), vec2<f32>(0.0, 0.0)); }
        case 1u: { return SuMat(vec2<f32>(1.0, 0.0), vec2<f32>(lam, 0.0), vec2<f32>(0.0, 0.0), vec2<f32>(1.0, 0.0)); }
        default: { return SuMat(vec2<f32>(1.0, 0.0), vec2<f32>(-lam, 0.0), vec2<f32>(0.0, 0.0), vec2<f32>(1.0, 0.0)); }
    }
}

fn hecke_inverse_of(k: u32) -> u32 {
    if (k == 1u) { return 2u; }
    if (k == 2u) { return 1u; }
    return 0u;
}

fn variation_hecke_group(p: vec2<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>, vc: ptr<function, f32>) -> vec2<f32> {
    let q = max(get_param(xform_id, variation_id, 0u), 3.0);
    let avoid = get_param(xform_id, variation_id, 1u) > 0.5;
    let dc_mode = u32(get_param(xform_id, variation_id, 2u));
    let dc_scale = get_param(xform_id, variation_id, 3u);
    let color_speed = get_param(xform_id, variation_id, 4u);
    let lam = 2.0 * cos(3.14159265359 / q);

    var k = min(u32(rng_nextf(rng) * 3.0), 2u);
    if (avoid) {
        let prev = u32(get_state(xform_id, variation_id, 0u));
        // Block only the strict inverse of a NON-involution: T after T⁻¹
        // and vice versa. S (its own inverse) is never blocked.
        if (prev >= 1u && prev < 3u && k == hecke_inverse_of(prev)) {
            k = (k + 1u) % 3u;
        }
    }
    set_state(xform_id, variation_id, 0u, f32(k));

    if (dc_mode == 1u) {
        var creg = get_state(xform_id, variation_id, 1u);
        creg = mix(creg, fract((f32(k) + 0.5) / 3.0 * dc_scale), color_speed);
        set_state(xform_id, variation_id, 1u, creg);
        *vc = creg;
    }

    var out = su_apply_plain(hecke_gen(k, lam), p);
    let symm = u32(get_param(xform_id, variation_id, 6u));
    if (symm == 1u) { if (rng_nextf(rng) < 0.5) { out = -out; } }
    else if (symm == 2u) { if (rng_nextf(rng) < 0.5) { out = vec2<f32>(out.x, -out.y); } }
    else if (symm == 3u) {
        let r = min(u32(rng_nextf(rng) * 4.0), 3u);
        if (r == 1u) { out = -out; }
        else if (r == 2u) { out = vec2<f32>(out.x, -out.y); }
        else if (r == 3u) { out = vec2<f32>(-out.x, out.y); }
    }
    return out;
}
"#;

const WGSL_3D: &str = r#"
fn hecke_gen(k: u32, lam: f32) -> SuMat {
    switch k {
        case 0u: { return SuMat(vec2<f32>(0.0, 0.0), vec2<f32>(-1.0, 0.0), vec2<f32>(1.0, 0.0), vec2<f32>(0.0, 0.0)); }
        case 1u: { return SuMat(vec2<f32>(1.0, 0.0), vec2<f32>(lam, 0.0), vec2<f32>(0.0, 0.0), vec2<f32>(1.0, 0.0)); }
        default: { return SuMat(vec2<f32>(1.0, 0.0), vec2<f32>(-lam, 0.0), vec2<f32>(0.0, 0.0), vec2<f32>(1.0, 0.0)); }
    }
}

fn hecke_inverse_of(k: u32) -> u32 {
    if (k == 1u) { return 2u; }
    if (k == 2u) { return 1u; }
    return 0u;
}

fn variation_hecke_group(p: vec3<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>, vc: ptr<function, f32>) -> vec3<f32> {
    let q = max(get_param(xform_id, variation_id, 0u), 3.0);
    let avoid = get_param(xform_id, variation_id, 1u) > 0.5;
    let dc_mode = u32(get_param(xform_id, variation_id, 2u));
    let dc_scale = get_param(xform_id, variation_id, 3u);
    let color_speed = get_param(xform_id, variation_id, 4u);
    let lam = 2.0 * cos(3.14159265359 / q);

    var k = min(u32(rng_nextf(rng) * 3.0), 2u);
    if (avoid) {
        let prev = u32(get_state(xform_id, variation_id, 0u));
        if (prev >= 1u && prev < 3u && k == hecke_inverse_of(prev)) {
            k = (k + 1u) % 3u;
        }
    }
    set_state(xform_id, variation_id, 0u, f32(k));

    if (dc_mode == 1u) {
        var creg = get_state(xform_id, variation_id, 1u);
        creg = mix(creg, fract((f32(k) + 0.5) / 3.0 * dc_scale), color_speed);
        set_state(xform_id, variation_id, 1u, creg);
        *vc = creg;
    }

    let g = hecke_gen(k, lam);
    let space = u32(get_param(xform_id, variation_id, 5u));
    var out: vec3<f32>;
    if (space == 1u) { out = su_apply_plain3(g, p); }
    else { out = vec3<f32>(su_apply_plain(g, p.xy), p.z); }
    let symm = u32(get_param(xform_id, variation_id, 6u));
    if (symm == 1u) { if (rng_nextf(rng) < 0.5) { out = vec3<f32>(-out.x, -out.y, out.z); } }
    else if (symm == 2u) { if (rng_nextf(rng) < 0.5) { out = vec3<f32>(out.x, -out.y, out.z); } }
    else if (symm == 3u) {
        let r = min(u32(rng_nextf(rng) * 4.0), 3u);
        if (r == 1u) { out = vec3<f32>(-out.x, -out.y, out.z); }
        else if (r == 2u) { out = vec3<f32>(out.x, -out.y, out.z); }
        else if (r == 3u) { out = vec3<f32>(-out.x, out.y, out.z); }
    }
    return out;
}
"#;
