//! `honeycomb` — hyperbolic honeycomb reflection walk, Schläfli
//! {p,q,r} (original).
//!
//! Renders the regular hyperbolic honeycombs of H³ — order-4
//! dodecahedral {5,3,4}, order-5 cubic {4,3,5}, icosahedral {3,5,3},
//! order-5 dodecahedral {5,3,5} — and every other [p,q,r] kaleidoscope
//! from three integer sliders. The full symmetry group of {p,q,r} is
//! generated by reflections in the 4 faces of its characteristic
//! simplex (the Coxeter orthoscheme), whose mirror normals follow in
//! closed form from the Gram matrix: successive Minkowski
//! Gram–Schmidt with ⟨n_i,n_j⟩ = −cos(π/m_ij) down the diagram
//! p—q—r. Each call lifts the incoming point from the ball model to
//! the hyperboloid (x²+y²+z²−t² = −1), applies `steps` random mirror
//! reflections — LINEAR maps `X → X − 2⟨X,n⟩n` under the Minkowski
//! inner product, never picking the same mirror twice in a row (that
//! would just undo) — and projects back.
//!
//! The chaos game walks the group orbit: whatever measure the flame's
//! other transforms build gets stamped through every fundamental
//! domain, accumulating toward the ball's boundary sphere. Because
//! Wythoff constructions differ only in where the seed sits relative
//! to the mirrors, this one variation covers every *uniform* honeycomb
//! of each [p,q,r] family (cantitruncated and friends included) — the
//! seed placement is the flame itself.
//!
//! `projection` selects the ball model: Poincaré (conformal,
//! `xyz/(1+t)`) or Beltrami–Klein (projective, straight mirror planes,
//! `xyz/t`). The lift matches the projection, so the fed-forward point
//! stays consistent. Non-compact slider combos (spherical/Euclidean)
//! degenerate gracefully: the last mirror's timelike component clamps
//! to 0 and the walk becomes a spherical/affine kaleidoscope.
//!
//! In 2D render mode the same machinery runs one dimension down:
//! {p,q} hyperbolic tilings of the disc from the first two sliders
//! (r is ignored).
//!
//! Direct color: *Mirror* — each of the 4 mirrors acts like a
//! transform with its own palette position, blended through the same
//! persistent color register as `menger`/`polychoron` (Color Speed 1 =
//! hard last-mirror assignment).
//!
//! No JWildfire/Apophysis counterpart (the 2D `hypertile` family are
//! fixed Möbius maps, not a general [p,q,r] walk) — original to this
//! project.

use crate::variations::{
    definition::{Feature, VariationDef, VariationParamDef},
    ParamType, VariationCategory, VariationPhase,
};
use crate::param;

pub static HONEYCOMB: VariationDef = VariationDef {
    name: "honeycomb",
    aliases: &[],
    display_name: "Hyperbolic Honeycomb",
    category: VariationCategory::Advanced2D,
    phase: VariationPhase::Normal,
    features: &[Feature::NeedsRng, Feature::WritesColor, Feature::AlwaysZ],
    init_param_count: 0,
    wgsl_init: None,
    // State slot 0: the color register for the Mirror color mode.
    state_count: 1,
    wgsl_state_init: None,
    parameters: &[
        param!("p", "P", int, 5.0, 2.0, 8.0, "First Schläfli number: the cell's face polygon ({5,3,4} = dodecahedral cells). Compact hyperbolic honeycombs: {5,3,4}, {4,3,5}, {3,5,3}, {5,3,5}. Other combinations still run — as spherical/Euclidean/non-discrete kaleidoscopes."),
        param!("q", "Q", int, 3.0, 2.0, 8.0, "Second Schläfli number: faces around each cell vertex ({p,q} is the cell polyhedron). In 2D render mode {p,q} is the tiling itself."),
        param!("r", "R", int, 4.0, 2.0, 8.0, "Third Schläfli number: cells around each edge. 4 = order-4 dodecahedral honeycomb at the defaults. Ignored in 2D render mode."),
        param!("size", "Size", float, 1.0, 0.1, 4.0, "Radius of the ball model in world units."),
        param!("steps", "Steps", int, 2.0, 1.0, 8.0, "Random mirror reflections per call. More steps walk deeper into the group per iteration (finer boundary detail for the same budget); even counts favor orientation-preserving words."),
        param!("projection", "Projection", enum, 0, &["Poincaré", "Beltrami–Klein"], "Ball model for the plotted (and fed-forward) point. Poincaré is conformal — cells shrink smoothly toward the boundary sphere. Beltrami–Klein is projective — mirror planes render as flat planes, cells as straight-edged polyhedra."),
        param!("dc_mode", "Color Mode", enum, 0, &["Off", "Mirror"], "Direct-color source (needs the transform's Direct Color > 0). Mirror: each of the 4 orthoscheme mirrors acts like a transform with its own palette position, blended through a persistent color register at Color Speed."),
        param!("dc_scale", "Color Scale", float, 1.0, 0.1, 8.0, "Palette-index multiplier for the Mirror colors (wrapped with fract)."),
        param!("color_speed", "Color Speed", float, 0.5, 0.0, 1.0, "Mirror color mode: how hard each reflection pulls the color register toward its mirror's palette position. Low = long trajectory blends, 1 = hard per-mirror assignment."),
        param!("seed", "Seed", enum, 0, &["Input", "Vertices", "Edges", "Faces"], "What the group walk stamps through the honeycomb. Input: the incoming flame measure (compose freely — any Wythoff decoration). Vertices: the honeycomb vertex — an array of dots. Edges: random points on the vertex-to-edge-center geodesic — the full ball-and-stick edge skeleton, the classic look of published honeycomb renders. Faces: random points on the orthoscheme's face triangle — the cell walls."),
    ],
    wgsl_2d: WGSL_2D,
    wgsl_3d: WGSL_3D,
};

const WGSL_3D: &str = r#"
fn honeycomb_mdot(a: vec4<f32>, b: vec4<f32>) -> f32 {
    return a.x * b.x + a.y * b.y + a.z * b.z - a.w * b.w;
}

fn variation_honeycomb(p: vec3<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>, vc: ptr<function, f32>) -> vec3<f32> {
    let sp = get_param(xform_id, variation_id, 0u);
    let sq = get_param(xform_id, variation_id, 1u);
    let sr = get_param(xform_id, variation_id, 2u);
    let size = max(get_param(xform_id, variation_id, 3u), 1e-6);
    let steps = i32(get_param(xform_id, variation_id, 4u));
    let projection = u32(get_param(xform_id, variation_id, 5u));
    let dc_mode = u32(get_param(xform_id, variation_id, 6u));
    let dc_scale = get_param(xform_id, variation_id, 7u);
    let color_speed = get_param(xform_id, variation_id, 8u);

    // Orthoscheme mirror normals for [p,q,r] by Minkowski Gram-Schmidt:
    // <n_i,n_j> = -cos(pi/m_ij) along the diagram, 0 for non-adjacent.
    // For compact hyperbolic combos the last normal picks up a timelike
    // component; the max(...) clamps degrade spherical/Euclidean combos
    // to a kaleidoscope through the origin instead of NaN.
    let pi = 3.14159265359;
    let cp = cos(pi / max(sp, 2.0));
    let cq = cos(pi / max(sq, 2.0));
    let cr = cos(pi / max(sr, 2.0));
    let s1 = sqrt(max(1.0 - cp * cp, 1e-6));
    let y2 = -cq / s1;
    let z2 = sqrt(max(1.0 - y2 * y2, 1e-6));
    let z3 = -cr / z2;
    let w3 = sqrt(max(z3 * z3 - 1.0, 0.0));
    var mirrors = array<vec4<f32>, 4>(
        vec4<f32>(1.0, 0.0, 0.0, 0.0),
        vec4<f32>(-cp, s1, 0.0, 0.0),
        vec4<f32>(0.0, y2, z2, 0.0),
        vec4<f32>(0.0, 0.0, z3, w3),
    );

    let seed_mode = u32(get_param(xform_id, variation_id, 9u));

    // Seed modes RESEED only occasionally: the walk continues from the
    // fed-forward point (already on the seeded skeleton) most calls, so
    // group depth grows without bound, while the periodic reseed keeps
    // re-injecting measure into the near shells. Restarting every call
    // would cap the word length at `steps` and draw only the first
    // shell of images.
    var x: vec4<f32>;
    if (seed_mode != 0u && rng_nextf(rng) < 0.1) {
        // Canonical seeds from the orthoscheme corners C_i (the corner
        // lying ON every mirror except i). C3 is the origin (cell
        // center); C0 is the honeycomb vertex. A point of the corner
        // simplex, pushed through the group, stamps the corresponding
        // element everywhere: C0 alone = vertex array, the C0-C1
        // segment = the full edge skeleton, the C0-C1-C2 triangle =
        // the cell walls. Geodesic sampling = Minkowski chord mix
        // renormalized onto the hyperboloid; the max() guard keeps
        // ideal corners (paracompact combos) finite.
        let zc = w3 / z3;
        let c0m = vec4<f32>(s1 * (-z2 * zc / y2) / max(cp, 1e-6), -z2 * zc / y2, zc, 1.0);
        let c1m = vec4<f32>(0.0, -z2 * zc / y2, zc, 1.0);
        let c2m = vec4<f32>(0.0, 0.0, zc, 1.0);
        var m = c0m;
        if (seed_mode == 2u) {
            m = mix(c0m, c1m, rng_nextf(rng));
        } else if (seed_mode == 3u) {
            let u = rng_nextf(rng);
            let v = rng_nextf(rng) * (1.0 - u);
            m = c0m + u * (c1m - c0m) + v * (c2m - c0m);
        }
        x = m / sqrt(max(-(m.x * m.x + m.y * m.y + m.z * m.z - m.w * m.w), 1e-6));
    } else {
        // Lift ball -> hyperboloid (x^2+y^2+z^2-t^2 = -1, t > 0).
        // Points outside the ball are folded in by inversion through
        // the boundary sphere first.
        var b = p / size;
        var r2 = dot(b, b);
        if (r2 >= 1.0) {
            b = b / (r2 + 1e-9);
            r2 = dot(b, b);
        }
        if (projection == 1u) {
            // Beltrami-Klein: t = 1/sqrt(1-r^2), xyz = b*t.
            let t = 1.0 / sqrt(max(1.0 - r2, 1e-9));
            x = vec4<f32>(b * t, t);
        } else {
            // Poincare: t = (1+r^2)/(1-r^2), xyz = 2b/(1-r^2).
            let d = max(1.0 - r2, 1e-9);
            x = vec4<f32>(2.0 * b / d, (1.0 + r2) / d);
        }
    }

    // Random mirror walk (never the same mirror twice in a row).
    var creg = get_state(xform_id, variation_id, 0u);
    var prev = 99u;
    for (var i = 0; i < steps; i = i + 1) {
        var idx = min(u32(rng_nextf(rng) * 4.0), 3u);
        if (idx == prev) {
            idx = (idx + 1u + min(u32(rng_nextf(rng) * 3.0), 2u)) % 4u;
        }
        prev = idx;
        let n = mirrors[idx];
        x = x - 2.0 * honeycomb_mdot(x, n) * n;
        if (dc_mode == 1u) {
            creg = mix(creg, fract((f32(idx) + 0.5) / 4.0 * dc_scale), color_speed);
        }
    }
    if (dc_mode == 1u) {
        set_state(xform_id, variation_id, 0u, creg);
        *vc = creg;
    }

    // Project back with the same model.
    let t = max(x.w, 1.0);
    if (projection == 1u) {
        return (x.xyz / t) * size;
    }
    return (x.xyz / (1.0 + t)) * size;
}
"#;

const WGSL_2D: &str = r#"
fn honeycomb_mdot2(a: vec3<f32>, b: vec3<f32>) -> f32 {
    return a.x * b.x + a.y * b.y - a.z * b.z;
}

fn variation_honeycomb(p: vec2<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>, vc: ptr<function, f32>) -> vec2<f32> {
    let sp = get_param(xform_id, variation_id, 0u);
    let sq = get_param(xform_id, variation_id, 1u);
    let size = max(get_param(xform_id, variation_id, 3u), 1e-6);
    let steps = i32(get_param(xform_id, variation_id, 4u));
    let projection = u32(get_param(xform_id, variation_id, 5u));
    let dc_mode = u32(get_param(xform_id, variation_id, 6u));
    let dc_scale = get_param(xform_id, variation_id, 7u);
    let color_speed = get_param(xform_id, variation_id, 8u);

    // Triangle-group [p,q] mirrors in R^(2,1) — the {p,q} tiling of
    // the hyperbolic disc (hyperbolic iff 1/p + 1/q < 1/2; other
    // combos degrade via the same clamps as 3D).
    let pi = 3.14159265359;
    let cp = cos(pi / max(sp, 2.0));
    let cq = cos(pi / max(sq, 2.0));
    let s1 = sqrt(max(1.0 - cp * cp, 1e-6));
    let y2 = -cq / s1;
    let w2 = sqrt(max(y2 * y2 - 1.0, 0.0));
    var mirrors = array<vec3<f32>, 3>(
        vec3<f32>(1.0, 0.0, 0.0),
        vec3<f32>(-cp, s1, 0.0),
        vec3<f32>(0.0, y2, w2),
    );

    let seed_mode = u32(get_param(xform_id, variation_id, 9u));

    var x: vec3<f32>;
    if (seed_mode != 0u && rng_nextf(rng) < 0.1) {
        // Triangle-group corners: C2 = origin (tile center), C1 = edge
        // center, C0 = tiling vertex. Edges mode draws the tiling's
        // edge skeleton; Faces fills the tiles.
        let yc = w2 / y2;
        let c0m = vec3<f32>(s1 * yc / max(cp, 1e-6), yc, 1.0);
        let c1m = vec3<f32>(0.0, yc, 1.0);
        let c2m = vec3<f32>(0.0, 0.0, 1.0);
        var m = c0m;
        if (seed_mode == 2u) {
            m = mix(c0m, c1m, rng_nextf(rng));
        } else if (seed_mode == 3u) {
            let u = rng_nextf(rng);
            let v = rng_nextf(rng) * (1.0 - u);
            m = c0m + u * (c1m - c0m) + v * (c2m - c0m);
        }
        x = m / sqrt(max(-(m.x * m.x + m.y * m.y - m.z * m.z), 1e-6));
    } else {
        var b = p / size;
        var r2 = dot(b, b);
        if (r2 >= 1.0) {
            b = b / (r2 + 1e-9);
            r2 = dot(b, b);
        }
        if (projection == 1u) {
            let t = 1.0 / sqrt(max(1.0 - r2, 1e-9));
            x = vec3<f32>(b * t, t);
        } else {
            let d = max(1.0 - r2, 1e-9);
            x = vec3<f32>(2.0 * b / d, (1.0 + r2) / d);
        }
    }

    var creg = get_state(xform_id, variation_id, 0u);
    var prev = 99u;
    for (var i = 0; i < steps; i = i + 1) {
        var idx = min(u32(rng_nextf(rng) * 3.0), 2u);
        if (idx == prev) {
            idx = (idx + 1u + min(u32(rng_nextf(rng) * 2.0), 1u)) % 3u;
        }
        prev = idx;
        let n = mirrors[idx];
        x = x - 2.0 * honeycomb_mdot2(x, n) * n;
        if (dc_mode == 1u) {
            creg = mix(creg, fract((f32(idx) + 0.5) / 3.0 * dc_scale), color_speed);
        }
    }
    if (dc_mode == 1u) {
        set_state(xform_id, variation_id, 0u, creg);
        *vc = creg;
    }

    let t = max(x.z, 1.0);
    if (projection == 1u) {
        return (x.xy / t) * size;
    }
    return (x.xy / (1.0 + t)) * size;
}
"#;
