//! `honeycomb` — hyperbolic honeycomb reflection walk, Schläfli
//! {p,q,r} (original).
//!
//! Renders the regular hyperbolic honeycombs of H³ — order-4
//! dodecahedral {5,3,4}, order-5 cubic {4,3,5}, icosahedral {3,5,3},
//! order-5 dodecahedral {5,3,5} — and every other [p,q,r] kaleidoscope
//! from three integer sliders. The full symmetry group of {p,q,r} is
//! generated by reflections in the 4 faces of its characteristic
//! simplex (the Coxeter orthoscheme), whose mirror normals follow in
//! closed form from the Gram matrix: successive Minkowski
//! Gram–Schmidt with ⟨n_i,n_j⟩ = −cos(π/m_ij) down the diagram
//! p—q—r. Each call lifts the incoming point from the ball model to
//! the hyperboloid (x²+y²+z²−t² = −1), applies `steps` random mirror
//! reflections — LINEAR maps `X → X − 2⟨X,n⟩n` under the Minkowski
//! inner product, never picking the same mirror twice in a row (that
//! would just undo) — and projects back.
//!
//! The chaos game walks the group orbit: whatever measure the flame's
//! other transforms build gets stamped through every fundamental
//! domain, accumulating toward the ball's boundary sphere. Because
//! Wythoff constructions differ only in where the seed sits relative
//! to the mirrors, this one variation covers every *uniform* honeycomb
//! of each [p,q,r] family (cantitruncated and friends included) — the
//! seed placement is the flame itself.
//!
//! `projection` selects the ball model: Poincaré (conformal,
//! `xyz/(1+t)`) or Beltrami–Klein (projective, straight mirror planes,
//! `xyz/t`). The lift matches the projection, so the fed-forward point
//! stays consistent. Non-compact slider combos (spherical/Euclidean)
//! degenerate gracefully: the last mirror's timelike component clamps
//! to 0 and the walk becomes a spherical/affine kaleidoscope.
//!
//! In 2D render mode the same machinery runs one dimension down:
//! {p,q} hyperbolic tilings of the disc from the first two sliders
//! (r is ignored).
//!
//! Direct color: *Mirror* — each of the 4 mirrors acts like a
//! transform with its own palette position, blended through the same
//! persistent color register as `menger`/`polychoron` (Color Speed 1 =
//! hard last-mirror assignment).
//!
//! No JWildfire/Apophysis counterpart (the 2D `hypertile` family are
//! fixed Möbius maps, not a general [p,q,r] walk) — original to this
//! project.

use crate::variations::{
    definition::{Feature, VariationDef, VariationParamDef},
    ParamType, VariationCategory, VariationPhase,
};
use crate::param;

pub static HONEYCOMB: VariationDef = VariationDef {
    name: "honeycomb",
    aliases: &[],
    display_name: "Hyperbolic Honeycomb",
    category: VariationCategory::Advanced2D,
    phase: VariationPhase::Normal,
    features: &[Feature::NeedsRng, Feature::WritesColor, Feature::AlwaysZ],
    init_param_count: 0,
    wgsl_init: None,
    // State slot 0: the color register for the Mirror color mode.
    // State slot 1: walk depth (word length since last reseed) for the
    // Steps color mode.
    state_count: 2,
    wgsl_state_init: None,
    parameters: &[
        param!("p", "P", int, 5.0, 2.0, 8.0, "First Schläfli number: the cell's face polygon ({5,3,4} = dodecahedral cells). Compact hyperbolic honeycombs: {5,3,4}, {4,3,5}, {3,5,3}, {5,3,5}. Other combinations still run — as spherical/Euclidean/non-discrete kaleidoscopes."),
        param!("q", "Q", int, 3.0, 2.0, 8.0, "Second Schläfli number: faces around each cell vertex ({p,q} is the cell polyhedron). In 2D render mode {p,q} is the tiling itself."),
        param!("r", "R", int, 4.0, 2.0, 8.0, "Third Schläfli number: cells around each edge. 4 = order-4 dodecahedral honeycomb at the defaults. Ignored in 2D render mode."),
        param!("size", "Size", float, 1.0, 0.1, 4.0, "Radius of the ball model in world units."),
        param!("steps", "Steps", int, 2.0, 1.0, 8.0, "Random mirror reflections per call. More steps walk deeper into the group per iteration (finer boundary detail for the same budget); even counts favor orientation-preserving words."),
        param!("projection", "Projection", enum, 0, &["Poincaré", "Beltrami–Klein", "Half-Space"], "Model of hyperbolic space for the plotted (and fed-forward) point. Poincaré: conformal ball — cells shrink toward the boundary sphere. Beltrami–Klein: projective ball — straight geodesics, flat cell walls. Half-Space: the honeycomb fills the region above an infinite floor plane, cells shrinking toward the floor and growing overhead (the classic 'honeycomb over a plane' renders; upper half-PLANE in 2D)."),
        param!("dc_mode", "Color Mode", enum, 0, &["Off", "Mirror", "Depth", "Steps"], "Direct-color source (needs the transform's Direct Color > 0). Mirror: each of the 4 orthoscheme mirrors acts like a transform with its own palette position, blended through a persistent color register at Color Speed. Depth: color by the output z (2D: disc radius). Steps: palette position sweeps start-to-end across the walk depth since the last reseed — the first shells get the first palette colors, the deepest get the last. Color Speed 1 spans the full palette over the mean walk length; Color Scale adds wrap cycles. (Seed modes; in Input mode depth never resets, so everything saturates at the final color.)"),
        param!("dc_scale", "Color Scale", float, 1.0, 0.1, 8.0, "Palette-index multiplier for the Mirror colors (wrapped with fract)."),
        param!("color_speed", "Color Speed", float, 0.5, 0.0, 1.0, "Mirror mode: how hard each reflection pulls the color register toward its mirror's palette position (low = long blends, 1 = hard assignment). Steps mode: how much of the palette the walk traverses — 1 sweeps the whole palette from first shell to the mean walk depth."),
        param!("seed", "Seed", enum, 0, &["Input", "Vertices", "Edges", "Faces"], "What the group walk stamps through the honeycomb. Input: the incoming flame measure (compose freely — any Wythoff decoration). Vertices: the honeycomb vertex — an array of dots. Edges: random points on the vertex-to-edge-center geodesic — the full ball-and-stick edge skeleton, the classic look of published honeycomb renders. Faces: random points on the orthoscheme's face triangle — the cell walls."),
        param!("thickness", "Thickness", float, 0.0, 0.0, 0.5, "Seed modes only: perturbs the seed before it lands on the hyperboloid, turning vertices into balls, edges into tubes, faces into slabs. The walk is isometric, so the tubes stay crisp and shrink toward the boundary exactly like the cells do — hyperbolically true thickness, unlike a plot-space jitter (which would also accumulate through the fed-forward walk)."),
        param!("variant", "Variant", enum, 0, &["Normal", "Rectified", "Truncated", "Bitruncated", "Cantellated", "Cantitruncated", "Runcitruncated", "Runcicantellated", "Omnitruncated"], "Wythoff variant of the honeycomb (seed modes only): which Coxeter-diagram nodes are ringed. The generator point sits ON every unringed mirror and equidistant from every ringed one; Vertices/Edges/Faces then stamp the chosen variant's elements. Normal = the plain {p,q,r}; Omnitruncated rings all four nodes. Input mode ignores this — there the flame itself is the generator."),
    ],
    wgsl_2d: WGSL_2D,
    wgsl_3d: WGSL_3D,
};

const WGSL_3D: &str = r#"
fn honeycomb_mdot(a: vec4<f32>, b: vec4<f32>) -> f32 {
    return a.x * b.x + a.y * b.y + a.z * b.z - a.w * b.w;
}

fn variation_honeycomb(p: vec3<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>, vc: ptr<function, f32>) -> vec3<f32> {
    let sp = get_param(xform_id, variation_id, 0u);
    let sq = get_param(xform_id, variation_id, 1u);
    let sr = get_param(xform_id, variation_id, 2u);
    let size = max(get_param(xform_id, variation_id, 3u), 1e-6);
    let steps = i32(get_param(xform_id, variation_id, 4u));
    let projection = u32(get_param(xform_id, variation_id, 5u));
    let dc_mode = u32(get_param(xform_id, variation_id, 6u));
    let dc_scale = get_param(xform_id, variation_id, 7u);
    let color_speed = get_param(xform_id, variation_id, 8u);

    // Orthoscheme mirror normals for [p,q,r] by Minkowski Gram-Schmidt:
    // <n_i,n_j> = -cos(pi/m_ij) along the diagram, 0 for non-adjacent.
    // For compact hyperbolic combos the last normal picks up a timelike
    // component; the max(...) clamps degrade spherical/Euclidean combos
    // to a kaleidoscope through the origin instead of NaN.
    let pi = 3.14159265359;
    let cp = cos(pi / max(sp, 2.0));
    let cq = cos(pi / max(sq, 2.0));
    let cr = cos(pi / max(sr, 2.0));
    let s1 = sqrt(max(1.0 - cp * cp, 1e-6));
    let y2 = -cq / s1;
    // Completing n2/n3 depends on the [p,q] cell subgroup's geometry
    // (a = 1 - y2^2 is, up to sign, the determinant of its 3x3 Gram):
    //   a > 0  — spherical cell polyhedron (all compact honeycombs):
    //            n2 stays spacelike in z, n3 carries the timelike part.
    //   a < 0  — hyperbolic-tiling cells ({6,4,3}, {7,3,r}, ...): n2
    //            itself needs the timelike component.
    //   a ~ 0  — Euclidean cells ({6,3,r} — the paracompact family):
    //            n2 is null-adjacent; z2 = w2 = 1 picks a frame, and
    //            n3 follows from (z3-w3)(z3+w3) = 1 with
    //            z2*z3 - w2*w3 = -cr.
    // The old code assumed the first case and clamped the rest into
    // garbage — p >= 6 never matched published renders.
    let a = 1.0 - y2 * y2;
    var z2 = 0.0;
    var w2 = 0.0;
    var z3 = 0.0;
    var w3 = 0.0;
    if (a > 1e-4) {
        z2 = sqrt(a);
        z3 = -cr / z2;
        w3 = sqrt(max(z3 * z3 - 1.0, 0.0));
    } else if (a < -1e-4) {
        w2 = sqrt(-a);
        w3 = cr / w2;
        z3 = sqrt(1.0 + w3 * w3);
    } else {
        z2 = 1.0;
        w2 = 1.0;
        let crs = max(cr, 1e-3);
        z3 = -0.5 * (crs + 1.0 / crs);
        w3 = 0.5 * (crs - 1.0 / crs);
    }
    var mirrors = array<vec4<f32>, 4>(
        vec4<f32>(1.0, 0.0, 0.0, 0.0),
        vec4<f32>(-cp, s1, 0.0, 0.0),
        vec4<f32>(0.0, y2, z2, w2),
        vec4<f32>(0.0, 0.0, z3, w3),
    );

    let seed_mode = u32(get_param(xform_id, variation_id, 9u));
    let thickness = get_param(xform_id, variation_id, 10u);
    let variant = u32(get_param(xform_id, variation_id, 11u));
    var depth = get_state(xform_id, variation_id, 1u);

    // Seed modes RESEED only occasionally: the walk continues from the
    // fed-forward point (already on the seeded skeleton) most calls, so
    // group depth grows without bound, while the periodic reseed keeps
    // re-injecting measure into the near shells. Restarting every call
    // would cap the word length at `steps` and draw only the first
    // shell of images.
    var x: vec4<f32>;
    if (seed_mode != 0u && rng_nextf(rng) < 0.1) {
        // Wythoff construction: the variant's ring mask says which
        // mirrors the generator point P is pushed OFF (equidistantly);
        // P lies ON every unringed mirror. Vertices = orbit of P;
        // each ringed mirror i contributes an edge orbit whose chamber
        // half is the geodesic P -> foot(P, mirror i); one further
        // projection spans a face fragment. For the Normal mask {0}
        // this reproduces the orthoscheme corners exactly (P = C0,
        // foot = C1, double projection = C2). Geodesic sampling =
        // Minkowski chord mix renormalized onto the hyperboloid; the
        // max() guards keep ideal elements (paracompact combos)
        // finite.
        var mask = 1u;
        switch variant {
            case 1u: { mask = 2u; }   // rectified        o-x-o-o
            case 2u: { mask = 3u; }   // truncated        x-x-o-o
            case 3u: { mask = 6u; }   // bitruncated      o-x-x-o
            case 4u: { mask = 5u; }   // cantellated      x-o-x-o
            case 5u: { mask = 7u; }   // cantitruncated   x-x-x-o
            case 6u: { mask = 11u; }  // runcitruncated   x-x-o-x
            case 7u: { mask = 13u; }  // runcicantellated x-o-x-x
            case 8u: { mask = 15u; }  // omnitruncated    x-x-x-x
            default: { mask = 1u; }   // normal           x-o-o-o
        }
        // Solve <P,n_i> = -1 (ringed) / 0 (unringed) down the
        // mirrors' triangular structure.
        let rc0 = select(0.0, -1.0, (mask & 1u) != 0u);
        let rc1 = select(0.0, -1.0, (mask & 2u) != 0u);
        let rc2 = select(0.0, -1.0, (mask & 4u) != 0u);
        let rc3 = select(0.0, -1.0, (mask & 8u) != 0u);
        let px = rc0;
        let py = (rc1 + cp * px) / s1;
        let b2 = rc2 - y2 * py;
        var dd = w2 * z3 - z2 * w3;
        if (abs(dd) < 1e-6) { dd = select(-1e-6, 1e-6, dd >= 0.0); }
        let pz = (w2 * rc3 - w3 * b2) / dd;
        let pw = (z2 * rc3 - z3 * b2) / dd;
        var pm = vec4<f32>(px, py, pz, pw);
        if (pm.w < 0.0) { pm = -pm; }
        let wp = pm / sqrt(max(-honeycomb_mdot(pm, pm), 1e-6));
        var m = wp;
        if (seed_mode >= 2u) {
            // Random ringed mirror -> edge foot (P projected onto it).
            let nring = f32(countOneBits(mask));
            var pick = i32(min(rng_nextf(rng) * nring, nring - 0.5));
            var mi = 0u;
            for (var i = 0u; i < 4u; i = i + 1u) {
                if ((mask & (1u << i)) != 0u) {
                    if (pick == 0) { mi = i; break; }
                    pick = pick - 1;
                }
            }
            var f1 = wp - honeycomb_mdot(wp, mirrors[mi]) * mirrors[mi];
            f1 = f1 / sqrt(max(-honeycomb_mdot(f1, f1), 1e-6));
            if (seed_mode == 2u) {
                m = mix(wp, f1, rng_nextf(rng));
            } else {
                // Face fragment: project the foot onto a second,
                // nondegenerate mirror.
                var mj = (mi + 1u + min(u32(rng_nextf(rng) * 3.0), 2u)) % 4u;
                for (var ttry = 0u; ttry < 3u; ttry = ttry + 1u) {
                    if (mj != mi && abs(honeycomb_mdot(f1, mirrors[mj])) > 1e-4) { break; }
                    mj = (mj + 1u) % 4u;
                    if (mj == mi) { mj = (mj + 1u) % 4u; }
                }
                var f2 = f1 - honeycomb_mdot(f1, mirrors[mj]) * mirrors[mj];
                f2 = f2 / sqrt(max(-honeycomb_mdot(f2, f2), 1e-6));
                let u = rng_nextf(rng);
                let v = rng_nextf(rng) * (1.0 - u);
                m = wp + u * (f1 - wp) + v * (f2 - wp);
            }
        }
        x = m / sqrt(max(-honeycomb_mdot(m, m), 1e-6));
        if (thickness > 0.0) {
            // Geodesic offset in the tangent space: move exact
            // hyperbolic distance `thickness` along a random tangent
            // direction (x' = cosh(T)x + sinh(T)u). This is a true
            // metric sphere SHELL around the seed — uniform tube
            // radius everywhere and all mass exactly at distance T
            // (hard walls). Offsetting in chordal coordinates instead
            // rescales with position (uneven thickness) and smears the
            // radial component into a translucent fill.
            let zz = rng_nextf(rng) * 2.0 - 1.0;
            let ph = rng_nextf(rng) * 6.28318530718;
            let rxy = sqrt(max(1.0 - zz * zz, 0.0));
            let d = vec3<f32>(rxy * cos(ph), rxy * sin(ph), zz);
            let c = dot(d, x.xyz);
            var u = vec4<f32>(d, 0.0) + c * x;
            u = u / sqrt(1.0 + c * c);
            x = cosh(thickness) * x + sinh(thickness) * u;
        }
        depth = 0.0;
    } else {
        // Lift ball -> hyperboloid (x^2+y^2+z^2-t^2 = -1, t > 0).
        // Points outside the ball are folded in by inversion through
        // the boundary sphere first.
        var b = p / size;
        var r2 = dot(b, b);
        if (r2 >= 1.0) {
            b = b / (r2 + 1e-9);
            r2 = dot(b, b);
        }
        if (projection == 1u) {
            // Beltrami-Klein: t = 1/sqrt(1-r^2), xyz = b*t.
            let t = 1.0 / sqrt(max(1.0 - r2, 1e-9));
            x = vec4<f32>(b * t, t);
        } else if (projection == 2u) {
            // Upper half-space (u,v,w), w = height above the floor
            // plane (z in world coords, folded positive): x = u/w,
            // y = v/w, t - z = 1/w, t + z from <X,X> = -1.
            let hb = p / size;
            let w = max(abs(hb.z), 1e-6);
            let hx = hb.x / w;
            let hy = hb.y / w;
            let s2 = hb.x * hb.x + hb.y * hb.y + w * w;
            let t = (1.0 + s2) / (2.0 * w);
            x = vec4<f32>(hx, hy, t - 1.0 / w, t);
        } else {
            // Poincare: t = (1+r^2)/(1-r^2), xyz = 2b/(1-r^2).
            let d = max(1.0 - r2, 1e-9);
            x = vec4<f32>(2.0 * b / d, (1.0 + r2) / d);
        }
    }

    // Random mirror walk (never the same mirror twice in a row).
    var creg = get_state(xform_id, variation_id, 0u);
    var prev = 99u;
    for (var i = 0; i < steps; i = i + 1) {
        var idx = min(u32(rng_nextf(rng) * 4.0), 3u);
        if (idx == prev) {
            idx = (idx + 1u + min(u32(rng_nextf(rng) * 3.0), 2u)) % 4u;
        }
        prev = idx;
        let n = mirrors[idx];
        x = x - 2.0 * honeycomb_mdot(x, n) * n;
        if (dc_mode == 1u) {
            creg = mix(creg, fract((f32(idx) + 0.5) / 4.0 * dc_scale), color_speed);
        }
    }
    if (dc_mode == 1u) {
        set_state(xform_id, variation_id, 0u, creg);
        *vc = creg;
    }

    // Project back with the same model.
    depth = depth + f32(steps);
    set_state(xform_id, variation_id, 1u, depth);
    let t = max(x.w, 1.0);
    var out: vec3<f32>;
    if (projection == 1u) {
        out = (x.xyz / t) * size;
    } else if (projection == 2u) {
        // Hyperboloid -> upper half-space: w = 1/(t - z), u = x*w,
        // v = y*w. t > |z| on the upper sheet, so t - z > 0.
        let iw = max(x.w - x.z, 1e-6);
        out = vec3<f32>(x.x / iw, x.y / iw, 1.0 / iw) * size;
    } else {
        out = (x.xyz / (1.0 + t)) * size;
    }
    if (dc_mode == 2u) {
        *vc = 0.5 + 0.5 * tanh(2.0 * dc_scale * out.z / size);
    } else if (dc_mode == 3u) {
        // Palette position sweeps 0 -> 1 across the MEAN walk length
        // (10 calls at 10% reseed probability x steps reflections per
        // call); deeper outliers clamp at the final color. Color Speed
        // scales the sweep (1 = full palette over the mean walk),
        // dc_scale adds wrap cycles.
        let t = clamp(depth * color_speed / (10.0 * f32(steps)), 0.0, 1.0);
        *vc = fract(min(t * dc_scale, 0.999));
    }
    return out;
}
"#;

const WGSL_2D: &str = r#"
fn honeycomb_mdot2(a: vec3<f32>, b: vec3<f32>) -> f32 {
    return a.x * b.x + a.y * b.y - a.z * b.z;
}

fn variation_honeycomb(p: vec2<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>, vc: ptr<function, f32>) -> vec2<f32> {
    let sp = get_param(xform_id, variation_id, 0u);
    let sq = get_param(xform_id, variation_id, 1u);
    let size = max(get_param(xform_id, variation_id, 3u), 1e-6);
    let steps = i32(get_param(xform_id, variation_id, 4u));
    let projection = u32(get_param(xform_id, variation_id, 5u));
    let dc_mode = u32(get_param(xform_id, variation_id, 6u));
    let dc_scale = get_param(xform_id, variation_id, 7u);
    let color_speed = get_param(xform_id, variation_id, 8u);
    let variant = u32(get_param(xform_id, variation_id, 11u));

    // Triangle-group [p,q] mirrors in R^(2,1) — the {p,q} tiling of
    // the hyperbolic disc (hyperbolic iff 1/p + 1/q < 1/2; other
    // combos degrade via the same clamps as 3D).
    let pi = 3.14159265359;
    let cp = cos(pi / max(sp, 2.0));
    let cq = cos(pi / max(sq, 2.0));
    let s1 = sqrt(max(1.0 - cp * cp, 1e-6));
    let y2 = -cq / s1;
    let w2 = sqrt(max(y2 * y2 - 1.0, 0.0));
    var mirrors = array<vec3<f32>, 3>(
        vec3<f32>(1.0, 0.0, 0.0),
        vec3<f32>(-cp, s1, 0.0),
        vec3<f32>(0.0, y2, w2),
    );

    let seed_mode = u32(get_param(xform_id, variation_id, 9u));
    let thickness = get_param(xform_id, variation_id, 10u);
    var depth = get_state(xform_id, variation_id, 1u);

    var x: vec3<f32>;
    if (seed_mode != 0u && rng_nextf(rng) < 0.1) {
        // Wythoff construction on the triangle group (see the 3D
        // body); the variant's low three ring bits apply.
        var mask = 1u;
        switch variant {
            case 1u: { mask = 2u; }
            case 2u: { mask = 3u; }
            case 3u: { mask = 6u; }
            case 4u: { mask = 5u; }
            case 5u, 8u: { mask = 7u; }
            case 6u: { mask = 3u; }
            case 7u: { mask = 5u; }
            default: { mask = 1u; }
        }
        let rc0 = select(0.0, -1.0, (mask & 1u) != 0u);
        let rc1 = select(0.0, -1.0, (mask & 2u) != 0u);
        let rc2 = select(0.0, -1.0, (mask & 4u) != 0u);
        let px = rc0;
        let py = (rc1 + cp * px) / s1;
        let w2s = max(w2, 1e-6);
        let pt = (y2 * py - rc2) / w2s;
        var pm = vec3<f32>(px, py, pt);
        if (pm.z < 0.0) { pm = -pm; }
        let wp = pm / sqrt(max(-honeycomb_mdot2(pm, pm), 1e-6));
        var m = wp;
        if (seed_mode >= 2u) {
            let nring = f32(countOneBits(mask));
            var pick = i32(min(rng_nextf(rng) * nring, nring - 0.5));
            var mi = 0u;
            for (var i = 0u; i < 3u; i = i + 1u) {
                if ((mask & (1u << i)) != 0u) {
                    if (pick == 0) { mi = i; break; }
                    pick = pick - 1;
                }
            }
            var f1 = wp - honeycomb_mdot2(wp, mirrors[mi]) * mirrors[mi];
            f1 = f1 / sqrt(max(-honeycomb_mdot2(f1, f1), 1e-6));
            if (seed_mode == 2u) {
                m = mix(wp, f1, rng_nextf(rng));
            } else {
                var mj = (mi + 1u + min(u32(rng_nextf(rng) * 2.0), 1u)) % 3u;
                for (var ttry = 0u; ttry < 2u; ttry = ttry + 1u) {
                    if (mj != mi && abs(honeycomb_mdot2(f1, mirrors[mj])) > 1e-4) { break; }
                    mj = (mj + 1u) % 3u;
                    if (mj == mi) { mj = (mj + 1u) % 3u; }
                }
                var f2 = f1 - honeycomb_mdot2(f1, mirrors[mj]) * mirrors[mj];
                f2 = f2 / sqrt(max(-honeycomb_mdot2(f2, f2), 1e-6));
                let u = rng_nextf(rng);
                let v = rng_nextf(rng) * (1.0 - u);
                m = wp + u * (f1 - wp) + v * (f2 - wp);
            }
        }
        x = m / sqrt(max(-honeycomb_mdot2(m, m), 1e-6));
        if (thickness > 0.0) {
            // Geodesic tangent offset — see the 3D body. In 2D the
            // random radius keeps the ribbon FILLED (a solid 2D ribbon
            // projects to itself, so a filled disc reads better than a
            // hollow ring here).
            let ph = rng_nextf(rng) * 6.28318530718;
            let d = vec2<f32>(cos(ph), sin(ph));
            let tt = thickness * sqrt(rng_nextf(rng));
            let c = dot(d, x.xy);
            var u = vec3<f32>(d, 0.0) + c * x;
            u = u / sqrt(1.0 + c * c);
            x = cosh(tt) * x + sinh(tt) * u;
        }
        depth = 0.0;
    } else {
        var b = p / size;
        var r2 = dot(b, b);
        if (r2 >= 1.0) {
            b = b / (r2 + 1e-9);
            r2 = dot(b, b);
        }
        if (projection == 1u) {
            let t = 1.0 / sqrt(max(1.0 - r2, 1e-9));
            x = vec3<f32>(b * t, t);
        } else if (projection == 2u) {
            // Upper half-plane: (u, w>0), x = u/w, t - y = 1/w.
            let hb = p / size;
            let w = max(abs(hb.y), 1e-6);
            let hx = hb.x / w;
            let s2 = hb.x * hb.x + w * w;
            let t = (1.0 + s2) / (2.0 * w);
            x = vec3<f32>(hx, t - 1.0 / w, t);
        } else {
            let d = max(1.0 - r2, 1e-9);
            x = vec3<f32>(2.0 * b / d, (1.0 + r2) / d);
        }
    }

    var creg = get_state(xform_id, variation_id, 0u);
    var prev = 99u;
    for (var i = 0; i < steps; i = i + 1) {
        var idx = min(u32(rng_nextf(rng) * 3.0), 2u);
        if (idx == prev) {
            idx = (idx + 1u + min(u32(rng_nextf(rng) * 2.0), 1u)) % 3u;
        }
        prev = idx;
        let n = mirrors[idx];
        x = x - 2.0 * honeycomb_mdot2(x, n) * n;
        if (dc_mode == 1u) {
            creg = mix(creg, fract((f32(idx) + 0.5) / 3.0 * dc_scale), color_speed);
        }
    }
    if (dc_mode == 1u) {
        set_state(xform_id, variation_id, 0u, creg);
        *vc = creg;
    }

    depth = depth + f32(steps);
    set_state(xform_id, variation_id, 1u, depth);
    let t = max(x.z, 1.0);
    var out: vec2<f32>;
    if (projection == 1u) {
        out = (x.xy / t) * size;
    } else if (projection == 2u) {
        let iw = max(x.z - x.y, 1e-6);
        out = vec2<f32>(x.x / iw, 1.0 / iw) * size;
    } else {
        out = (x.xy / (1.0 + t)) * size;
    }
    if (dc_mode == 2u) {
        *vc = fract(length(out) / size * dc_scale);
    } else if (dc_mode == 3u) {
        // Palette position sweeps 0 -> 1 across the MEAN walk length
        // (10 calls at 10% reseed probability x steps reflections per
        // call); deeper outliers clamp at the final color. Color Speed
        // scales the sweep (1 = full palette over the mean walk),
        // dc_scale adds wrap cycles.
        let t = clamp(depth * color_speed / (10.0 * f32(steps)), 0.0, 1.0);
        *vc = fract(min(t * dc_scale, 0.999));
    }
    return out;
}
"#;
