//! Band Symmetry Group variations sym_bg1..sym_bg7 (Jesus Sosa).
//!
//! GENERATED by scripts/gen_sym_ng.py from
//! `output/variation-jwf-source/SymBandG*Func.java`. Do not edit by hand —
//! re-run the generator instead.
//!
//! Each is a band/frieze symmetry base shape: pick one of N baked 2x2
//! symmetry affines at random, apply it (optionally after a fixed offset),
//! and accumulate. The matrices and the init() translation formulas are
//! transcribed from JWildfire's Java (its default/CPU renderer). Reference:
//! McGregor & Watt, "The Art of Graphics for the IBM PC", pp. 162-205.

use crate::variations::{
    definition::{Feature, VariationDef, VariationParamDef},
    ParamType, VariationCategory, VariationPhase,
};
use crate::param;

/// Band Symmetry Group variations sym_bg1..sym_bg7
///
/// # Authors
/// - Jesus Sosa
pub static SYM_BG1: VariationDef = VariationDef {
    name: "sym_bg1",
    aliases: &[],
    display_name: "Sym BG1",
    category: VariationCategory::Plugin,
    phase: VariationPhase::Any,
    features: &[Feature::NeedsRng],
    parameters: &[
        param!("stepx", "stepx", unlimited_float, 0.0, -100.0, 100.0, "Band-symmetry parameter (see JWildfire SymBandG1)."),
        param!("stepy", "stepy", unlimited_float, 0.0, -100.0, 100.0, "Band-symmetry parameter (see JWildfire SymBandG1)."),
    ],
    init_param_count: 0,
    wgsl_init: None,
    state_count: 0,
    wgsl_state_init: None,
    wgsl_2d: r#"
fn variation_sym_bg1(p: vec2<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec2<f32> {
    let stepx = get_param(xform_id, variation_id, 0u);
    let stepy = get_param(xform_id, variation_id, 1u);
    let zx = p.x;
    let zy = p.y;
    let idx = i32(floor(rng_nextf(rng) * 2.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 1.0; b = 0.0; c = -stepx/2.0-1.0; d = 0.0; e = 1.0; ff = -stepy/2.0; }
        default: { a = 1.0; b = 0.0; c = stepx/2.0; d = 0.0; e = 1.0; ff = stepy/2.0; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec2<f32>(ox, oy);
}
"#,
    wgsl_3d: r#"
fn variation_sym_bg1(p: vec3<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec3<f32> {
    let stepx = get_param(xform_id, variation_id, 0u);
    let stepy = get_param(xform_id, variation_id, 1u);
    let zx = p.x;
    let zy = p.y;
    let idx = i32(floor(rng_nextf(rng) * 2.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 1.0; b = 0.0; c = -stepx/2.0-1.0; d = 0.0; e = 1.0; ff = -stepy/2.0; }
        default: { a = 1.0; b = 0.0; c = stepx/2.0; d = 0.0; e = 1.0; ff = stepy/2.0; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec3<f32>(ox, oy, p.z);
}
"#,
};

/// Band Symmetry Group variations sym_bg1..sym_bg7
///
/// # Authors
/// - Jesus Sosa
pub static SYM_BG2: VariationDef = VariationDef {
    name: "sym_bg2",
    aliases: &[],
    display_name: "Sym BG2",
    category: VariationCategory::Plugin,
    phase: VariationPhase::Any,
    features: &[Feature::NeedsRng],
    parameters: &[
        param!("stepx", "stepx", unlimited_float, 0.0, -100.0, 100.0, "Band-symmetry parameter (see JWildfire SymBandG2)."),
        param!("stepy", "stepy", unlimited_float, 0.0, -100.0, 100.0, "Band-symmetry parameter (see JWildfire SymBandG2)."),
    ],
    init_param_count: 0,
    wgsl_init: None,
    state_count: 0,
    wgsl_state_init: None,
    wgsl_2d: r#"
fn variation_sym_bg2(p: vec2<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec2<f32> {
    let stepx = get_param(xform_id, variation_id, 0u);
    let stepy = get_param(xform_id, variation_id, 1u);
    let zx = p.x;
    let zy = p.y;
    let idx = i32(floor(rng_nextf(rng) * 2.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 1.0; b = 0.0; c = -stepx/2.0-1.0; d = 0.0; e = 1.0; ff = -stepy/2.0; }
        default: { a = 1.0; b = 0.0; c = stepx/2.0; d = 0.0; e = -1.0; ff = stepy/2.0+ 1.0; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec2<f32>(ox, oy);
}
"#,
    wgsl_3d: r#"
fn variation_sym_bg2(p: vec3<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec3<f32> {
    let stepx = get_param(xform_id, variation_id, 0u);
    let stepy = get_param(xform_id, variation_id, 1u);
    let zx = p.x;
    let zy = p.y;
    let idx = i32(floor(rng_nextf(rng) * 2.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 1.0; b = 0.0; c = -stepx/2.0-1.0; d = 0.0; e = 1.0; ff = -stepy/2.0; }
        default: { a = 1.0; b = 0.0; c = stepx/2.0; d = 0.0; e = -1.0; ff = stepy/2.0+ 1.0; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec3<f32>(ox, oy, p.z);
}
"#,
};

/// Band Symmetry Group variations sym_bg1..sym_bg7
///
/// # Authors
/// - Jesus Sosa
pub static SYM_BG3: VariationDef = VariationDef {
    name: "sym_bg3",
    aliases: &[],
    display_name: "Sym BG3",
    category: VariationCategory::Plugin,
    phase: VariationPhase::Any,
    features: &[Feature::NeedsRng],
    parameters: &[
        param!("stepx", "stepx", unlimited_float, 0.0, -100.0, 100.0, "Band-symmetry parameter (see JWildfire SymBandG3)."),
        param!("stepy", "stepy", unlimited_float, 0.0, -100.0, 100.0, "Band-symmetry parameter (see JWildfire SymBandG3)."),
    ],
    init_param_count: 0,
    wgsl_init: None,
    state_count: 0,
    wgsl_state_init: None,
    wgsl_2d: r#"
fn variation_sym_bg3(p: vec2<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec2<f32> {
    let stepx = get_param(xform_id, variation_id, 0u);
    let stepy = get_param(xform_id, variation_id, 1u);
    let zx = p.x;
    let zy = p.y;
    let idx = i32(floor(rng_nextf(rng) * 2.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 1.0; b = 0.0; c = -stepx/2.0 - 1.0; d = 0.0; e = 1.0; ff = -stepy/2.0 - 0.5; }
        default: { a = -1.0; b = 0.0; c = stepx/2.0 + 1.0; d = 0.0; e = -1.0; ff = stepy/2.0 + 0.5; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec2<f32>(ox, oy);
}
"#,
    wgsl_3d: r#"
fn variation_sym_bg3(p: vec3<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec3<f32> {
    let stepx = get_param(xform_id, variation_id, 0u);
    let stepy = get_param(xform_id, variation_id, 1u);
    let zx = p.x;
    let zy = p.y;
    let idx = i32(floor(rng_nextf(rng) * 2.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 1.0; b = 0.0; c = -stepx/2.0 - 1.0; d = 0.0; e = 1.0; ff = -stepy/2.0 - 0.5; }
        default: { a = -1.0; b = 0.0; c = stepx/2.0 + 1.0; d = 0.0; e = -1.0; ff = stepy/2.0 + 0.5; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec3<f32>(ox, oy, p.z);
}
"#,
};

/// Band Symmetry Group variations sym_bg1..sym_bg7
///
/// # Authors
/// - Jesus Sosa
pub static SYM_BG4: VariationDef = VariationDef {
    name: "sym_bg4",
    aliases: &[],
    display_name: "Sym BG4",
    category: VariationCategory::Plugin,
    phase: VariationPhase::Any,
    features: &[Feature::NeedsRng],
    parameters: &[
        param!("stepx", "stepx", unlimited_float, 0.0, -100.0, 100.0, "Band-symmetry parameter (see JWildfire SymBandG4)."),
        param!("stepy", "stepy", unlimited_float, 0.0, -100.0, 100.0, "Band-symmetry parameter (see JWildfire SymBandG4)."),
    ],
    init_param_count: 0,
    wgsl_init: None,
    state_count: 0,
    wgsl_state_init: None,
    wgsl_2d: r#"
fn variation_sym_bg4(p: vec2<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec2<f32> {
    let stepx = get_param(xform_id, variation_id, 0u);
    let stepy = get_param(xform_id, variation_id, 1u);
    let zx = p.x;
    let zy = p.y;
    let idx = i32(floor(rng_nextf(rng) * 2.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 1.0; b = 0.0; c = -stepx/2.0 - 1.0; d = 0.0; e = 1.0; ff = -stepy/2.0 - 0.5; }
        default: { a = -1.0; b = 0.0; c = stepx/2.0 + 1.0; d = 0.0; e = 1.0; ff = stepy/2.0 + 0.5; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec2<f32>(ox, oy);
}
"#,
    wgsl_3d: r#"
fn variation_sym_bg4(p: vec3<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec3<f32> {
    let stepx = get_param(xform_id, variation_id, 0u);
    let stepy = get_param(xform_id, variation_id, 1u);
    let zx = p.x;
    let zy = p.y;
    let idx = i32(floor(rng_nextf(rng) * 2.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 1.0; b = 0.0; c = -stepx/2.0 - 1.0; d = 0.0; e = 1.0; ff = -stepy/2.0 - 0.5; }
        default: { a = -1.0; b = 0.0; c = stepx/2.0 + 1.0; d = 0.0; e = 1.0; ff = stepy/2.0 + 0.5; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec3<f32>(ox, oy, p.z);
}
"#,
};

/// Band Symmetry Group variations sym_bg1..sym_bg7
///
/// # Authors
/// - Jesus Sosa
pub static SYM_BG5: VariationDef = VariationDef {
    name: "sym_bg5",
    aliases: &[],
    display_name: "Sym BG5",
    category: VariationCategory::Plugin,
    phase: VariationPhase::Any,
    features: &[Feature::NeedsRng],
    parameters: &[
        param!("stepx", "stepx", unlimited_float, 0.0, -100.0, 100.0, "Band-symmetry parameter (see JWildfire SymBandG5)."),
        param!("stepy", "stepy", unlimited_float, 0.0, -100.0, 100.0, "Band-symmetry parameter (see JWildfire SymBandG5)."),
    ],
    init_param_count: 0,
    wgsl_init: None,
    state_count: 0,
    wgsl_state_init: None,
    wgsl_2d: r#"
fn variation_sym_bg5(p: vec2<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec2<f32> {
    let stepx = get_param(xform_id, variation_id, 0u);
    let stepy = get_param(xform_id, variation_id, 1u);
    let zx = p.x;
    let zy = p.y;
    let idx = i32(floor(rng_nextf(rng) * 2.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 1.0; b = 0.0; c = -stepx/2.0 - 1.0; d = 0.0; e = 1.0; ff = -stepy/2.0 - 0.5; }
        default: { a = 1.0; b = 0.0; c = stepx/2.0 - 1.0; d = 0.0; e = -1.0; ff = stepy/2.0 + 0.5; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec2<f32>(ox, oy);
}
"#,
    wgsl_3d: r#"
fn variation_sym_bg5(p: vec3<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec3<f32> {
    let stepx = get_param(xform_id, variation_id, 0u);
    let stepy = get_param(xform_id, variation_id, 1u);
    let zx = p.x;
    let zy = p.y;
    let idx = i32(floor(rng_nextf(rng) * 2.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 1.0; b = 0.0; c = -stepx/2.0 - 1.0; d = 0.0; e = 1.0; ff = -stepy/2.0 - 0.5; }
        default: { a = 1.0; b = 0.0; c = stepx/2.0 - 1.0; d = 0.0; e = -1.0; ff = stepy/2.0 + 0.5; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec3<f32>(ox, oy, p.z);
}
"#,
};

/// Band Symmetry Group variations sym_bg1..sym_bg7
///
/// # Authors
/// - Jesus Sosa
pub static SYM_BG6: VariationDef = VariationDef {
    name: "sym_bg6",
    aliases: &[],
    display_name: "Sym BG6",
    category: VariationCategory::Plugin,
    phase: VariationPhase::Any,
    features: &[Feature::NeedsRng],
    parameters: &[
        param!("stepx", "stepx", unlimited_float, 0.0, -100.0, 100.0, "Band-symmetry parameter (see JWildfire SymBandG6)."),
        param!("stepy", "stepy", unlimited_float, 0.0, -100.0, 100.0, "Band-symmetry parameter (see JWildfire SymBandG6)."),
    ],
    init_param_count: 0,
    wgsl_init: None,
    state_count: 0,
    wgsl_state_init: None,
    wgsl_2d: r#"
fn variation_sym_bg6(p: vec2<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec2<f32> {
    let stepx = get_param(xform_id, variation_id, 0u);
    let stepy = get_param(xform_id, variation_id, 1u);
    let zx = p.x;
    let zy = p.y;
    let idx = i32(floor(rng_nextf(rng) * 4.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 1.0; b = 0.0; c = -stepx/2.0 - 1.0; d = 0.0; e = 1.0; ff = -stepy/2.0 - 0.5; }
        case 1: { a = -1.0; b = 0.0; c = stepx/2.0 + 1.0; d = 0.0; e = 1.0; ff = stepy/2.0 - 0.5; }
        case 2: { a = 1.0; b = 0.0; c = -stepx/2.0 - 1.0; d = 0.0; e = -1.0; ff = -stepy/2.0 + 0.5; }
        default: { a = -1.0; b = 0.0; c = stepx/2.0 + 1.0; d = 0.0; e = -1.0; ff = stepy/2.0 + 0.5; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec2<f32>(ox, oy);
}
"#,
    wgsl_3d: r#"
fn variation_sym_bg6(p: vec3<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec3<f32> {
    let stepx = get_param(xform_id, variation_id, 0u);
    let stepy = get_param(xform_id, variation_id, 1u);
    let zx = p.x;
    let zy = p.y;
    let idx = i32(floor(rng_nextf(rng) * 4.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 1.0; b = 0.0; c = -stepx/2.0 - 1.0; d = 0.0; e = 1.0; ff = -stepy/2.0 - 0.5; }
        case 1: { a = -1.0; b = 0.0; c = stepx/2.0 + 1.0; d = 0.0; e = 1.0; ff = stepy/2.0 - 0.5; }
        case 2: { a = 1.0; b = 0.0; c = -stepx/2.0 - 1.0; d = 0.0; e = -1.0; ff = -stepy/2.0 + 0.5; }
        default: { a = -1.0; b = 0.0; c = stepx/2.0 + 1.0; d = 0.0; e = -1.0; ff = stepy/2.0 + 0.5; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec3<f32>(ox, oy, p.z);
}
"#,
};

/// Band Symmetry Group variations sym_bg1..sym_bg7
///
/// # Authors
/// - Jesus Sosa
pub static SYM_BG7: VariationDef = VariationDef {
    name: "sym_bg7",
    aliases: &[],
    display_name: "Sym BG7",
    category: VariationCategory::Plugin,
    phase: VariationPhase::Any,
    features: &[Feature::NeedsRng],
    parameters: &[
        param!("stepx", "stepx", unlimited_float, 0.0, -100.0, 100.0, "Band-symmetry parameter (see JWildfire SymBandG7)."),
        param!("stepy", "stepy", unlimited_float, 0.0, -100.0, 100.0, "Band-symmetry parameter (see JWildfire SymBandG7)."),
    ],
    init_param_count: 0,
    wgsl_init: None,
    state_count: 0,
    wgsl_state_init: None,
    wgsl_2d: r#"
fn variation_sym_bg7(p: vec2<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec2<f32> {
    let stepx = get_param(xform_id, variation_id, 0u);
    let stepy = get_param(xform_id, variation_id, 1u);
    let zx = p.x;
    let zy = p.y;
    let idx = i32(floor(rng_nextf(rng) * 4.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 1.0; b = 0.0; c = -stepx/2.0 - 2.0; d = 0.0; e = 1.0; ff = -stepy/2.0 - 0.5; }
        case 1: { a = -1.0; b = 0.0; c = stepx/2.0 + 2.0; d = 0.0; e = 1.0; ff = stepy/2.0 - 0.5; }
        case 2: { a = 1.0; b = 0.0; c = stepx/2.0; d = 0.0; e = -1.0; ff = stepy/2.0 + 0.5; }
        default: { a = -1.0; b = 0.0; c = -stepx/2.0; d = 0.0; e = -1.0; ff = -stepy/2.0 + 0.5; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec2<f32>(ox, oy);
}
"#,
    wgsl_3d: r#"
fn variation_sym_bg7(p: vec3<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec3<f32> {
    let stepx = get_param(xform_id, variation_id, 0u);
    let stepy = get_param(xform_id, variation_id, 1u);
    let zx = p.x;
    let zy = p.y;
    let idx = i32(floor(rng_nextf(rng) * 4.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 1.0; b = 0.0; c = -stepx/2.0 - 2.0; d = 0.0; e = 1.0; ff = -stepy/2.0 - 0.5; }
        case 1: { a = -1.0; b = 0.0; c = stepx/2.0 + 2.0; d = 0.0; e = 1.0; ff = stepy/2.0 - 0.5; }
        case 2: { a = 1.0; b = 0.0; c = stepx/2.0; d = 0.0; e = -1.0; ff = stepy/2.0 + 0.5; }
        default: { a = -1.0; b = 0.0; c = -stepx/2.0; d = 0.0; e = -1.0; ff = -stepy/2.0 + 0.5; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec3<f32>(ox, oy, p.z);
}
"#,
};
