//! Network Symmetry Group variations sym_ng1..sym_ng17 (Jesus Sosa).
//!
//! GENERATED by scripts/gen_sym_ng.py from
//! `output/variation-jwf-source/SymNetG*Func.java`. Do not edit by hand —
//! re-run the generator instead.
//!
//! Each is a band/frieze symmetry base shape: pick one of N baked 2x2
//! symmetry affines at random, apply it (optionally after a fixed offset),
//! and accumulate. The matrices and the init() translation formulas are
//! transcribed from JWildfire's Java (its default/CPU renderer). Reference:
//! McGregor & Watt, "The Art of Graphics for the IBM PC", pp. 162-205.

use crate::variations::{
    definition::{Feature, VariationDef, VariationParamDef},
    ParamType, VariationCategory, VariationPhase,
};
use crate::param;

pub static SYM_NG1: VariationDef = VariationDef {
    name: "sym_ng1",
    aliases: &[],
    display_name: "Sym NG1",
    category: VariationCategory::Plugin,
    phase: VariationPhase::Any,
    features: &[Feature::NeedsRng],
    parameters: &[
        param!("stepx", "stepx", unlimited_float, 0.5, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG1)."),
        param!("stepy", "stepy", unlimited_float, 0.5, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG1)."),
    ],
    init_param_count: 0,
    wgsl_init: None,
    state_count: 0,
    wgsl_state_init: None,
    wgsl_2d: r#"
fn variation_sym_ng1(p: vec2<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec2<f32> {
    let stepx = get_param(xform_id, variation_id, 0u);
    let stepy = get_param(xform_id, variation_id, 1u);
    let zx = p.x;
    let zy = p.y;
    let idx = i32(floor(rng_nextf(rng) * 2.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 1.0; b = 0.0; c = -stepx/2.0; d = 0.0; e = 1.0; ff = -stepy/2.0; }
        default: { a = 1.0; b = 0.0; c = stepx/2.0; d = 0.0; e = 1.0; ff = stepy/2.0; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec2<f32>(ox, oy);
}
"#,
    wgsl_3d: r#"
fn variation_sym_ng1(p: vec3<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec3<f32> {
    let stepx = get_param(xform_id, variation_id, 0u);
    let stepy = get_param(xform_id, variation_id, 1u);
    let zx = p.x;
    let zy = p.y;
    let idx = i32(floor(rng_nextf(rng) * 2.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 1.0; b = 0.0; c = -stepx/2.0; d = 0.0; e = 1.0; ff = -stepy/2.0; }
        default: { a = 1.0; b = 0.0; c = stepx/2.0; d = 0.0; e = 1.0; ff = stepy/2.0; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec3<f32>(ox, oy, p.z);
}
"#,
};

pub static SYM_NG2: VariationDef = VariationDef {
    name: "sym_ng2",
    aliases: &[],
    display_name: "Sym NG2",
    category: VariationCategory::Plugin,
    phase: VariationPhase::Any,
    features: &[Feature::NeedsRng],
    parameters: &[
        param!("stepx", "stepx", unlimited_float, 2.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG2)."),
        param!("stepy", "stepy", unlimited_float, 2.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG2)."),
    ],
    init_param_count: 0,
    wgsl_init: None,
    state_count: 0,
    wgsl_state_init: None,
    wgsl_2d: r#"
fn variation_sym_ng2(p: vec2<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec2<f32> {
    let stepx = get_param(xform_id, variation_id, 0u);
    let stepy = get_param(xform_id, variation_id, 1u);
    let zx = p.x;
    let zy = p.y;
    let idx = i32(floor(rng_nextf(rng) * 2.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 1.0; b = 0.0; c = -stepx/2.0; d = 0.0; e = 1.0; ff = -stepy/2.0; }
        default: { a = 1.0; b = 0.0; c = stepx/2.0; d = 0.0; e = -1.0; ff = stepy/2.0; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec2<f32>(ox, oy);
}
"#,
    wgsl_3d: r#"
fn variation_sym_ng2(p: vec3<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec3<f32> {
    let stepx = get_param(xform_id, variation_id, 0u);
    let stepy = get_param(xform_id, variation_id, 1u);
    let zx = p.x;
    let zy = p.y;
    let idx = i32(floor(rng_nextf(rng) * 2.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 1.0; b = 0.0; c = -stepx/2.0; d = 0.0; e = 1.0; ff = -stepy/2.0; }
        default: { a = 1.0; b = 0.0; c = stepx/2.0; d = 0.0; e = -1.0; ff = stepy/2.0; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec3<f32>(ox, oy, p.z);
}
"#,
};

pub static SYM_NG3: VariationDef = VariationDef {
    name: "sym_ng3",
    aliases: &[],
    display_name: "Sym NG3",
    category: VariationCategory::Plugin,
    phase: VariationPhase::Any,
    features: &[Feature::NeedsRng],
    parameters: &[
        param!("sepx", "sepx", unlimited_float, 0.5, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG3)."),
        param!("sepy", "sepy", unlimited_float, 0.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG3)."),
        param!("step", "step", unlimited_float, 2.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG3)."),
    ],
    init_param_count: 0,
    wgsl_init: None,
    state_count: 0,
    wgsl_state_init: None,
    wgsl_2d: r#"
fn variation_sym_ng3(p: vec2<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec2<f32> {
    let sepx = get_param(xform_id, variation_id, 0u);
    let sepy = get_param(xform_id, variation_id, 1u);
    let step = get_param(xform_id, variation_id, 2u);
    let zx = p.x;
    let zy = p.y;
    let idx = i32(floor(rng_nextf(rng) * 2.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 1.0; b = 0.0; c = -sepx - step/2.0; d = 0.0; e = 1.0; ff = -sepy - step/2.0; }
        default: { a = -1.0; b = 0.0; c = sepx + step/2.0; d = 0.0; e = -1.0; ff = sepy + step/2.0; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec2<f32>(ox, oy);
}
"#,
    wgsl_3d: r#"
fn variation_sym_ng3(p: vec3<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec3<f32> {
    let sepx = get_param(xform_id, variation_id, 0u);
    let sepy = get_param(xform_id, variation_id, 1u);
    let step = get_param(xform_id, variation_id, 2u);
    let zx = p.x;
    let zy = p.y;
    let idx = i32(floor(rng_nextf(rng) * 2.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 1.0; b = 0.0; c = -sepx - step/2.0; d = 0.0; e = 1.0; ff = -sepy - step/2.0; }
        default: { a = -1.0; b = 0.0; c = sepx + step/2.0; d = 0.0; e = -1.0; ff = sepy + step/2.0; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec3<f32>(ox, oy, p.z);
}
"#,
};

pub static SYM_NG4: VariationDef = VariationDef {
    name: "sym_ng4",
    aliases: &[],
    display_name: "Sym NG4",
    category: VariationCategory::Plugin,
    phase: VariationPhase::Any,
    features: &[Feature::NeedsRng],
    parameters: &[
        param!("sepx", "sepx", unlimited_float, 0.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG4)."),
        param!("sepy", "sepy", unlimited_float, 0.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG4)."),
        param!("stepx", "stepx", unlimited_float, 0.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG4)."),
        param!("stepy", "stepy", unlimited_float, 0.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG4)."),
    ],
    init_param_count: 0,
    wgsl_init: None,
    state_count: 0,
    wgsl_state_init: None,
    wgsl_2d: r#"
fn variation_sym_ng4(p: vec2<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec2<f32> {
    let sepx = get_param(xform_id, variation_id, 0u);
    let sepy = get_param(xform_id, variation_id, 1u);
    let stepx = get_param(xform_id, variation_id, 2u);
    let stepy = get_param(xform_id, variation_id, 3u);
    let sx = sepx/2.0;
    let sy = sepy/2.0;
    let stpx = stepx/2.0;
    let stpy = stepy/2.0;
    let zx = p.x;
    let zy = p.y;
    let idx = i32(floor(rng_nextf(rng) * 4.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 1.0; b = 0.0; c = -sx - 2.0- stpx; d = 0.0; e = 1.0; ff = sy - 1.5- stpy; }
        case 1: { a = -1.0; b = 0.0; c = sx -stpx; d = 0.0; e = -1.0; ff = -sy - 0.5 -stpy; }
        case 2: { a = 1.0; b = 0.0; c = -sx +stpx; d = 0.0; e = -1.0; ff = -sy + 0.5 +stpy; }
        default: { a = -1.0; b = 0.0; c = sx + 2.0 +stpx; d = 0.0; e = 1.0; ff = sy - 0.5 +stpy; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec2<f32>(ox, oy);
}
"#,
    wgsl_3d: r#"
fn variation_sym_ng4(p: vec3<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec3<f32> {
    let sepx = get_param(xform_id, variation_id, 0u);
    let sepy = get_param(xform_id, variation_id, 1u);
    let stepx = get_param(xform_id, variation_id, 2u);
    let stepy = get_param(xform_id, variation_id, 3u);
    let sx = sepx/2.0;
    let sy = sepy/2.0;
    let stpx = stepx/2.0;
    let stpy = stepy/2.0;
    let zx = p.x;
    let zy = p.y;
    let idx = i32(floor(rng_nextf(rng) * 4.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 1.0; b = 0.0; c = -sx - 2.0- stpx; d = 0.0; e = 1.0; ff = sy - 1.5- stpy; }
        case 1: { a = -1.0; b = 0.0; c = sx -stpx; d = 0.0; e = -1.0; ff = -sy - 0.5 -stpy; }
        case 2: { a = 1.0; b = 0.0; c = -sx +stpx; d = 0.0; e = -1.0; ff = -sy + 0.5 +stpy; }
        default: { a = -1.0; b = 0.0; c = sx + 2.0 +stpx; d = 0.0; e = 1.0; ff = sy - 0.5 +stpy; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec3<f32>(ox, oy, p.z);
}
"#,
};

pub static SYM_NG5: VariationDef = VariationDef {
    name: "sym_ng5",
    aliases: &[],
    display_name: "Sym NG5",
    category: VariationCategory::Plugin,
    phase: VariationPhase::Any,
    features: &[Feature::NeedsRng],
    parameters: &[
        param!("sepx", "sepx", unlimited_float, 0.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG5)."),
        param!("sepy", "sepy", unlimited_float, 0.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG5)."),
        param!("stepx", "stepx", unlimited_float, 0.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG5)."),
    ],
    init_param_count: 0,
    wgsl_init: None,
    state_count: 0,
    wgsl_state_init: None,
    wgsl_2d: r#"
fn variation_sym_ng5(p: vec2<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec2<f32> {
    let sepx = get_param(xform_id, variation_id, 0u);
    let sepy = get_param(xform_id, variation_id, 1u);
    let stepx = get_param(xform_id, variation_id, 2u);
    let zx = p.x;
    let zy = p.y;
    let idx = i32(floor(rng_nextf(rng) * 4.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 1.0; b = 0.0; c = -sepx-2.0-stepx/2.0; d = 0.0; e = 1.0; ff = sepy-0.5; }
        case 1: { a = -1.0; b = 0.0; c = sepx - stepx/2.0; d = 0.0; e = -1.0; ff = -sepy-0.5; }
        case 2: { a = 1.0; b = 0.0; c = -sepx + stepx/2.0; d = 0.0; e = -1.0; ff = -sepy-0.5; }
        default: { a = -1.0; b = 0.0; c = 2.0 + sepx + stepx/2.0; d = 0.0; e = 1.0; ff = sepy -0.5; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec2<f32>(ox, oy);
}
"#,
    wgsl_3d: r#"
fn variation_sym_ng5(p: vec3<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec3<f32> {
    let sepx = get_param(xform_id, variation_id, 0u);
    let sepy = get_param(xform_id, variation_id, 1u);
    let stepx = get_param(xform_id, variation_id, 2u);
    let zx = p.x;
    let zy = p.y;
    let idx = i32(floor(rng_nextf(rng) * 4.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 1.0; b = 0.0; c = -sepx-2.0-stepx/2.0; d = 0.0; e = 1.0; ff = sepy-0.5; }
        case 1: { a = -1.0; b = 0.0; c = sepx - stepx/2.0; d = 0.0; e = -1.0; ff = -sepy-0.5; }
        case 2: { a = 1.0; b = 0.0; c = -sepx + stepx/2.0; d = 0.0; e = -1.0; ff = -sepy-0.5; }
        default: { a = -1.0; b = 0.0; c = 2.0 + sepx + stepx/2.0; d = 0.0; e = 1.0; ff = sepy -0.5; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec3<f32>(ox, oy, p.z);
}
"#,
};

pub static SYM_NG6: VariationDef = VariationDef {
    name: "sym_ng6",
    aliases: &[],
    display_name: "Sym NG6",
    category: VariationCategory::Plugin,
    phase: VariationPhase::Any,
    features: &[Feature::NeedsRng],
    parameters: &[
        param!("sepy", "sepy", unlimited_float, 0.1, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG6)."),
        param!("stepx", "stepx", unlimited_float, 1.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG6)."),
        param!("stepy", "stepy", unlimited_float, 1.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG6)."),
    ],
    init_param_count: 0,
    wgsl_init: None,
    state_count: 0,
    wgsl_state_init: None,
    wgsl_2d: r#"
fn variation_sym_ng6(p: vec2<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec2<f32> {
    let sepy = get_param(xform_id, variation_id, 0u);
    let stepx = get_param(xform_id, variation_id, 1u);
    let stepy = get_param(xform_id, variation_id, 2u);
    let zx = p.x;
    let zy = p.y;
    let idx = i32(floor(rng_nextf(rng) * 4.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 1.0; b = 0.0; c = -stepx/2.0; d = 0.0; e = 1.0; ff = -stepy/2.0 +sepy/2.0; }
        case 1: { a = 1.0; b = 0.0; c = -stepx/2.0; d = 0.0; e = -1.0; ff = -stepy/2.0-sepy/2.0; }
        case 2: { a = 1.0; b = 0.0; c = stepx/2.0; d = 0.0; e = 1.0; ff = stepy/2.0+sepy/2.0; }
        default: { a = 1.0; b = 0.0; c = stepx/2.0; d = 0.0; e = -1.0; ff = stepy/2.0-sepy/2.0; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec2<f32>(ox, oy);
}
"#,
    wgsl_3d: r#"
fn variation_sym_ng6(p: vec3<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec3<f32> {
    let sepy = get_param(xform_id, variation_id, 0u);
    let stepx = get_param(xform_id, variation_id, 1u);
    let stepy = get_param(xform_id, variation_id, 2u);
    let zx = p.x;
    let zy = p.y;
    let idx = i32(floor(rng_nextf(rng) * 4.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 1.0; b = 0.0; c = -stepx/2.0; d = 0.0; e = 1.0; ff = -stepy/2.0 +sepy/2.0; }
        case 1: { a = 1.0; b = 0.0; c = -stepx/2.0; d = 0.0; e = -1.0; ff = -stepy/2.0-sepy/2.0; }
        case 2: { a = 1.0; b = 0.0; c = stepx/2.0; d = 0.0; e = 1.0; ff = stepy/2.0+sepy/2.0; }
        default: { a = 1.0; b = 0.0; c = stepx/2.0; d = 0.0; e = -1.0; ff = stepy/2.0-sepy/2.0; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec3<f32>(ox, oy, p.z);
}
"#,
};

pub static SYM_NG7: VariationDef = VariationDef {
    name: "sym_ng7",
    aliases: &[],
    display_name: "Sym NG7",
    category: VariationCategory::Plugin,
    phase: VariationPhase::Any,
    features: &[Feature::NeedsRng],
    parameters: &[
        param!("sepx", "sepx", unlimited_float, 0.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG7)."),
        param!("sepy", "sepy", unlimited_float, 0.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG7)."),
    ],
    init_param_count: 0,
    wgsl_init: None,
    state_count: 0,
    wgsl_state_init: None,
    wgsl_2d: r#"
fn variation_sym_ng7(p: vec2<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec2<f32> {
    let sepx = get_param(xform_id, variation_id, 0u);
    let sepy = get_param(xform_id, variation_id, 1u);
    let zx = p.x;
    let zy = p.y;
    let idx = i32(floor(rng_nextf(rng) * 2.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 1.0; b = 0.0; c = -sepx/2.0; d = 0.0; e = 1.0; ff = sepy/2.0; }
        default: { a = 1.0; b = 0.0; c = sepx/2.0; d = 0.0; e = -1.0; ff = -sepy/2.0; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec2<f32>(ox, oy);
}
"#,
    wgsl_3d: r#"
fn variation_sym_ng7(p: vec3<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec3<f32> {
    let sepx = get_param(xform_id, variation_id, 0u);
    let sepy = get_param(xform_id, variation_id, 1u);
    let zx = p.x;
    let zy = p.y;
    let idx = i32(floor(rng_nextf(rng) * 2.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 1.0; b = 0.0; c = -sepx/2.0; d = 0.0; e = 1.0; ff = sepy/2.0; }
        default: { a = 1.0; b = 0.0; c = sepx/2.0; d = 0.0; e = -1.0; ff = -sepy/2.0; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec3<f32>(ox, oy, p.z);
}
"#,
};

pub static SYM_NG8: VariationDef = VariationDef {
    name: "sym_ng8",
    aliases: &[],
    display_name: "Sym NG8",
    category: VariationCategory::Plugin,
    phase: VariationPhase::Any,
    features: &[Feature::NeedsRng],
    parameters: &[
        param!("sepx", "sepx", unlimited_float, 0.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG8)."),
        param!("sepy", "sepy", unlimited_float, 0.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG8)."),
        param!("skewx", "skewx", unlimited_float, 0.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG8)."),
        param!("skewy", "skewy", unlimited_float, 0.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG8)."),
    ],
    init_param_count: 0,
    wgsl_init: None,
    state_count: 0,
    wgsl_state_init: None,
    wgsl_2d: r#"
fn variation_sym_ng8(p: vec2<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec2<f32> {
    let sepx = get_param(xform_id, variation_id, 0u);
    let sepy = get_param(xform_id, variation_id, 1u);
    let skewx = get_param(xform_id, variation_id, 2u);
    let skewy = get_param(xform_id, variation_id, 3u);
    let zx = p.x;
    let zy = p.y;
    let idx = i32(floor(rng_nextf(rng) * 8.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 1.0; b = 0.0; c = -1.0-sepx/2.0 - skewx/2.0; d = 0.0; e = -1.0; ff = -sepy/2.0 -skewy/2.0; }
        case 1: { a = -1.0; b = 0.0; c = 1.0 + sepx/2.0- skewx/2.0; d = 0.0; e = 1.0; ff = sepy/2.0-skewy/2.0; }
        case 2: { a = -1.0; b = 0.0; c = 1.0 + sepx/2.0- skewx/2.0; d = 0.0; e = -1.0; ff = -sepy/2.0-skewy/2.0; }
        case 3: { a = 1.0; b = 0.0; c = -1.0 -sepx/2.0- skewx/2.0; d = 0.0; e = 1.0; ff = sepy/2.0-skewy/2.0; }
        case 4: { a = 1.0; b = 0.0; c = -1.0-sepx/2.0 + skewx/2.0; d = 0.0; e = -1.0; ff = -sepy/2.0 + skewy/2.0; }
        case 5: { a = -1.0; b = 0.0; c = 1.0 + sepx/2.0 + skewx/2.0; d = 0.0; e = 1.0; ff = sepy/2.0 + skewy/2.0; }
        case 6: { a = -1.0; b = 0.0; c = 1.0 + sepx/2.0 +skewx/2.0; d = 0.0; e = -1.0; ff = -sepy/2.0 + skewy/2.0; }
        default: { a = 1.0; b = 0.0; c = -1.0 -sepx/2.0 + skewx/2.0; d = 0.0; e = 1.0; ff = sepy/2.0 + skewy/2.0; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec2<f32>(ox, oy);
}
"#,
    wgsl_3d: r#"
fn variation_sym_ng8(p: vec3<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec3<f32> {
    let sepx = get_param(xform_id, variation_id, 0u);
    let sepy = get_param(xform_id, variation_id, 1u);
    let skewx = get_param(xform_id, variation_id, 2u);
    let skewy = get_param(xform_id, variation_id, 3u);
    let zx = p.x;
    let zy = p.y;
    let idx = i32(floor(rng_nextf(rng) * 8.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 1.0; b = 0.0; c = -1.0-sepx/2.0 - skewx/2.0; d = 0.0; e = -1.0; ff = -sepy/2.0 -skewy/2.0; }
        case 1: { a = -1.0; b = 0.0; c = 1.0 + sepx/2.0- skewx/2.0; d = 0.0; e = 1.0; ff = sepy/2.0-skewy/2.0; }
        case 2: { a = -1.0; b = 0.0; c = 1.0 + sepx/2.0- skewx/2.0; d = 0.0; e = -1.0; ff = -sepy/2.0-skewy/2.0; }
        case 3: { a = 1.0; b = 0.0; c = -1.0 -sepx/2.0- skewx/2.0; d = 0.0; e = 1.0; ff = sepy/2.0-skewy/2.0; }
        case 4: { a = 1.0; b = 0.0; c = -1.0-sepx/2.0 + skewx/2.0; d = 0.0; e = -1.0; ff = -sepy/2.0 + skewy/2.0; }
        case 5: { a = -1.0; b = 0.0; c = 1.0 + sepx/2.0 + skewx/2.0; d = 0.0; e = 1.0; ff = sepy/2.0 + skewy/2.0; }
        case 6: { a = -1.0; b = 0.0; c = 1.0 + sepx/2.0 +skewx/2.0; d = 0.0; e = -1.0; ff = -sepy/2.0 + skewy/2.0; }
        default: { a = 1.0; b = 0.0; c = -1.0 -sepx/2.0 + skewx/2.0; d = 0.0; e = 1.0; ff = sepy/2.0 + skewy/2.0; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec3<f32>(ox, oy, p.z);
}
"#,
};

pub static SYM_NG9: VariationDef = VariationDef {
    name: "sym_ng9",
    aliases: &[],
    display_name: "Sym NG9",
    category: VariationCategory::Plugin,
    phase: VariationPhase::Any,
    features: &[Feature::NeedsRng],
    parameters: &[
        param!("sepx", "sepx", unlimited_float, 0.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG9)."),
        param!("sepy", "sepy", unlimited_float, 0.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG9)."),
    ],
    init_param_count: 0,
    wgsl_init: None,
    state_count: 0,
    wgsl_state_init: None,
    wgsl_2d: r#"
fn variation_sym_ng9(p: vec2<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec2<f32> {
    let sepx = get_param(xform_id, variation_id, 0u);
    let sepy = get_param(xform_id, variation_id, 1u);
    let zx = p.x;
    let zy = p.y;
    let idx = i32(floor(rng_nextf(rng) * 4.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 1.0; b = 0.0; c = sepx/2.0; d = 0.0; e = -1.0; ff = -sepy/2.0; }
        case 1: { a = -1.0; b = 0.0; c = -sepx/2.0; d = 0.0; e = 1.0; ff = sepy/2.0; }
        case 2: { a = -1.0; b = 0.0; c = -sepx/2.0; d = 0.0; e = -1.0; ff = -sepy/2.0; }
        default: { a = 1.0; b = 0.0; c = sepx/2.0; d = 0.0; e = 1.0; ff = sepy/2.0; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec2<f32>(ox, oy);
}
"#,
    wgsl_3d: r#"
fn variation_sym_ng9(p: vec3<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec3<f32> {
    let sepx = get_param(xform_id, variation_id, 0u);
    let sepy = get_param(xform_id, variation_id, 1u);
    let zx = p.x;
    let zy = p.y;
    let idx = i32(floor(rng_nextf(rng) * 4.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 1.0; b = 0.0; c = sepx/2.0; d = 0.0; e = -1.0; ff = -sepy/2.0; }
        case 1: { a = -1.0; b = 0.0; c = -sepx/2.0; d = 0.0; e = 1.0; ff = sepy/2.0; }
        case 2: { a = -1.0; b = 0.0; c = -sepx/2.0; d = 0.0; e = -1.0; ff = -sepy/2.0; }
        default: { a = 1.0; b = 0.0; c = sepx/2.0; d = 0.0; e = 1.0; ff = sepy/2.0; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec3<f32>(ox, oy, p.z);
}
"#,
};

pub static SYM_NG10: VariationDef = VariationDef {
    name: "sym_ng10",
    aliases: &[],
    display_name: "Sym NG10",
    category: VariationCategory::Plugin,
    phase: VariationPhase::Any,
    features: &[Feature::NeedsRng],
    parameters: &[
        param!("space", "space", unlimited_float, 0.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG10)."),
        param!("spacex", "spacex", unlimited_float, 0.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG10)."),
        param!("spacey", "spacey", unlimited_float, 0.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG10)."),
    ],
    init_param_count: 0,
    wgsl_init: None,
    state_count: 0,
    wgsl_state_init: None,
    wgsl_2d: r#"
fn variation_sym_ng10(p: vec2<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec2<f32> {
    let space = get_param(xform_id, variation_id, 0u);
    let spacex = get_param(xform_id, variation_id, 1u);
    let spacey = get_param(xform_id, variation_id, 2u);
    let zx = p.x + (space);
    let zy = p.y + (space);
    let idx = i32(floor(rng_nextf(rng) * 4.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = -1.0; b = 0.0; c = -spacex/2.0; d = 0.0; e = -1.0; ff = -spacey/2.0; }
        case 1: { a = 0.0; b = 1.0; c = -spacex/2.0; d = -1.0; e = -0.0; ff = -spacey/2.0; }
        case 2: { a = -0.0; b = -1.0; c = spacex/2.0; d = 1.0; e = -0.0; ff = spacey/2.0; }
        default: { a = 1.0; b = - 0.0; c = spacex/2.0; d = 0.0; e = 1.0; ff = spacey/2.0; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec2<f32>(ox, oy);
}
"#,
    wgsl_3d: r#"
fn variation_sym_ng10(p: vec3<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec3<f32> {
    let space = get_param(xform_id, variation_id, 0u);
    let spacex = get_param(xform_id, variation_id, 1u);
    let spacey = get_param(xform_id, variation_id, 2u);
    let zx = p.x + (space);
    let zy = p.y + (space);
    let idx = i32(floor(rng_nextf(rng) * 4.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = -1.0; b = 0.0; c = -spacex/2.0; d = 0.0; e = -1.0; ff = -spacey/2.0; }
        case 1: { a = 0.0; b = 1.0; c = -spacex/2.0; d = -1.0; e = -0.0; ff = -spacey/2.0; }
        case 2: { a = -0.0; b = -1.0; c = spacex/2.0; d = 1.0; e = -0.0; ff = spacey/2.0; }
        default: { a = 1.0; b = - 0.0; c = spacex/2.0; d = 0.0; e = 1.0; ff = spacey/2.0; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec3<f32>(ox, oy, p.z);
}
"#,
};

pub static SYM_NG11: VariationDef = VariationDef {
    name: "sym_ng11",
    aliases: &[],
    display_name: "Sym NG11",
    category: VariationCategory::Plugin,
    phase: VariationPhase::Any,
    features: &[Feature::NeedsRng],
    parameters: &[
        param!("space", "space", unlimited_float, 0.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG11)."),
        param!("spacex", "spacex", unlimited_float, 0.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG11)."),
        param!("spacey", "spacey", unlimited_float, 0.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG11)."),
        param!("stepx", "stepx", unlimited_float, 1.5, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG11)."),
        param!("stepy", "stepy", unlimited_float, 1.5, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG11)."),
    ],
    init_param_count: 0,
    wgsl_init: None,
    state_count: 0,
    wgsl_state_init: None,
    wgsl_2d: r#"
fn variation_sym_ng11(p: vec2<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec2<f32> {
    let space = get_param(xform_id, variation_id, 0u);
    let spacex = get_param(xform_id, variation_id, 1u);
    let spacey = get_param(xform_id, variation_id, 2u);
    let stepx = get_param(xform_id, variation_id, 3u);
    let stepy = get_param(xform_id, variation_id, 4u);
    let zx = p.x + (space);
    let zy = p.y + (space);
    let idx = i32(floor(rng_nextf(rng) * 8.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 1.0; b = 0.0; c = spacex + stepx/2.0; d = 0.0; e = 1.0; ff = spacey + stepy/2.0; }
        case 1: { a = -1.0; b = 0.0; c = -spacex + stepx/2.0; d = 0.0; e = -1.0; ff = -spacey + stepy/2.0; }
        case 2: { a = -0.0; b = 1.0; c = spacex + stepx/2.0; d = -1.0; e = -0.0; ff = -spacey + stepy/2.0; }
        case 3: { a = -0.0; b = -1.0; c = -spacex + stepx/2.0; d = 1.0; e = -0.0; ff = spacey + stepy/2.0; }
        case 4: { a = -1.0; b = 0.0; c = -spacex -stepx/2.0; d = 0.0; e = 1.0; ff = spacey- stepy/2.0; }
        case 5: { a = -0.0; b = -1.0; c = -spacex -stepx/2.0; d = -1.0; e = -0.0; ff = -spacey- stepy/2.0; }
        case 6: { a = -0.0; b = 1.0; c = spacex -stepx/2.0; d = 1.0; e = -0.0; ff = spacey -stepy/2.0; }
        default: { a = 1.0; b = 0.0; c = spacex -stepx/2.0; d = 0.0; e = -1.0; ff = -spacey -stepy/2.0; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec2<f32>(ox, oy);
}
"#,
    wgsl_3d: r#"
fn variation_sym_ng11(p: vec3<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec3<f32> {
    let space = get_param(xform_id, variation_id, 0u);
    let spacex = get_param(xform_id, variation_id, 1u);
    let spacey = get_param(xform_id, variation_id, 2u);
    let stepx = get_param(xform_id, variation_id, 3u);
    let stepy = get_param(xform_id, variation_id, 4u);
    let zx = p.x + (space);
    let zy = p.y + (space);
    let idx = i32(floor(rng_nextf(rng) * 8.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 1.0; b = 0.0; c = spacex + stepx/2.0; d = 0.0; e = 1.0; ff = spacey + stepy/2.0; }
        case 1: { a = -1.0; b = 0.0; c = -spacex + stepx/2.0; d = 0.0; e = -1.0; ff = -spacey + stepy/2.0; }
        case 2: { a = -0.0; b = 1.0; c = spacex + stepx/2.0; d = -1.0; e = -0.0; ff = -spacey + stepy/2.0; }
        case 3: { a = -0.0; b = -1.0; c = -spacex + stepx/2.0; d = 1.0; e = -0.0; ff = spacey + stepy/2.0; }
        case 4: { a = -1.0; b = 0.0; c = -spacex -stepx/2.0; d = 0.0; e = 1.0; ff = spacey- stepy/2.0; }
        case 5: { a = -0.0; b = -1.0; c = -spacex -stepx/2.0; d = -1.0; e = -0.0; ff = -spacey- stepy/2.0; }
        case 6: { a = -0.0; b = 1.0; c = spacex -stepx/2.0; d = 1.0; e = -0.0; ff = spacey -stepy/2.0; }
        default: { a = 1.0; b = 0.0; c = spacex -stepx/2.0; d = 0.0; e = -1.0; ff = -spacey -stepy/2.0; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec3<f32>(ox, oy, p.z);
}
"#,
};

pub static SYM_NG12: VariationDef = VariationDef {
    name: "sym_ng12",
    aliases: &[],
    display_name: "Sym NG12",
    category: VariationCategory::Plugin,
    phase: VariationPhase::Any,
    features: &[Feature::NeedsRng],
    parameters: &[
        param!("space", "space", unlimited_float, 0.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG12)."),
        param!("spacex", "spacex", unlimited_float, 0.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG12)."),
        param!("spacey", "spacey", unlimited_float, 0.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG12)."),
    ],
    init_param_count: 0,
    wgsl_init: None,
    state_count: 0,
    wgsl_state_init: None,
    wgsl_2d: r#"
fn variation_sym_ng12(p: vec2<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec2<f32> {
    let space = get_param(xform_id, variation_id, 0u);
    let spacex = get_param(xform_id, variation_id, 1u);
    let spacey = get_param(xform_id, variation_id, 2u);
    let zx = p.x + (space);
    let zy = p.y + (space);
    let idx = i32(floor(rng_nextf(rng) * 8.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 1.0; b = 0.0; c = spacex; d = 0.0; e = 1.0; ff = spacey; }
        case 1: { a = -1.0; b = 0.0; c = -spacex; d = 0.0; e = -1.0; ff = -spacey; }
        case 2: { a = -0.0; b = 1.0; c = spacex; d = -1.0; e = -0.0; ff = -spacey; }
        case 3: { a = -0.0; b = -1.0; c = -spacex; d = 1.0; e = -0.0; ff = spacey; }
        case 4: { a = -1.0; b = 0.0; c = -spacex; d = 0.0; e = 1.0; ff = spacey; }
        case 5: { a = -0.0; b = -1.0; c = -spacex; d = -1.0; e = -0.0; ff = -spacey; }
        case 6: { a = -0.0; b = 1.0; c = spacex; d = 1.0; e = -0.0; ff = spacey; }
        default: { a = 1.0; b = 0.0; c = spacex; d = 0.0; e = -1.0; ff = -spacey; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec2<f32>(ox, oy);
}
"#,
    wgsl_3d: r#"
fn variation_sym_ng12(p: vec3<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec3<f32> {
    let space = get_param(xform_id, variation_id, 0u);
    let spacex = get_param(xform_id, variation_id, 1u);
    let spacey = get_param(xform_id, variation_id, 2u);
    let zx = p.x + (space);
    let zy = p.y + (space);
    let idx = i32(floor(rng_nextf(rng) * 8.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 1.0; b = 0.0; c = spacex; d = 0.0; e = 1.0; ff = spacey; }
        case 1: { a = -1.0; b = 0.0; c = -spacex; d = 0.0; e = -1.0; ff = -spacey; }
        case 2: { a = -0.0; b = 1.0; c = spacex; d = -1.0; e = -0.0; ff = -spacey; }
        case 3: { a = -0.0; b = -1.0; c = -spacex; d = 1.0; e = -0.0; ff = spacey; }
        case 4: { a = -1.0; b = 0.0; c = -spacex; d = 0.0; e = 1.0; ff = spacey; }
        case 5: { a = -0.0; b = -1.0; c = -spacex; d = -1.0; e = -0.0; ff = -spacey; }
        case 6: { a = -0.0; b = 1.0; c = spacex; d = 1.0; e = -0.0; ff = spacey; }
        default: { a = 1.0; b = 0.0; c = spacex; d = 0.0; e = -1.0; ff = -spacey; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec3<f32>(ox, oy, p.z);
}
"#,
};

pub static SYM_NG13: VariationDef = VariationDef {
    name: "sym_ng13",
    aliases: &[],
    display_name: "Sym NG13",
    category: VariationCategory::Plugin,
    phase: VariationPhase::Any,
    features: &[Feature::NeedsRng],
    parameters: &[
        param!("radius", "radius", unlimited_float, 0.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG13)."),
        param!("stepx", "stepx", unlimited_float, 0.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG13)."),
        param!("stepy", "stepy", unlimited_float, 0.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG13)."),
    ],
    init_param_count: 0,
    wgsl_init: None,
    state_count: 0,
    wgsl_state_init: None,
    wgsl_2d: r#"
fn variation_sym_ng13(p: vec2<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec2<f32> {
    let radius = get_param(xform_id, variation_id, 0u);
    let stepx = get_param(xform_id, variation_id, 1u);
    let stepy = get_param(xform_id, variation_id, 2u);
    let sx = stepx/2.0;
    let sy = stepy/2.0;
    let spacex = sqrt(radius*radius/2.0);
    let spacey = spacex;
    let zx = p.x + (spacex);
    let zy = p.y + (spacey);
    let idx = i32(floor(rng_nextf(rng) * 6.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 1.0; b = 0.0; c = -sx; d = 0.0; e = -1.0; ff = -sy; }
        case 1: { a = -0.5; b = -0.866; c = -sx; d = -0.866; e = 0.50; ff = -sy; }
        case 2: { a = -0.5; b = 0.866; c = -sx; d = 0.866; e = 0.50; ff = -sy; }
        case 3: { a = 1.0; b = 0.0; c = sx; d = 0.0; e = -1.0; ff = sy; }
        case 4: { a = -0.5; b = -0.866; c = sx; d = -0.866; e = 0.50; ff = sy; }
        default: { a = -0.5; b = 0.866; c = sx; d = 0.866; e = 0.50; ff = sy; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec2<f32>(ox, oy);
}
"#,
    wgsl_3d: r#"
fn variation_sym_ng13(p: vec3<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec3<f32> {
    let radius = get_param(xform_id, variation_id, 0u);
    let stepx = get_param(xform_id, variation_id, 1u);
    let stepy = get_param(xform_id, variation_id, 2u);
    let sx = stepx/2.0;
    let sy = stepy/2.0;
    let spacex = sqrt(radius*radius/2.0);
    let spacey = spacex;
    let zx = p.x + (spacex);
    let zy = p.y + (spacey);
    let idx = i32(floor(rng_nextf(rng) * 6.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 1.0; b = 0.0; c = -sx; d = 0.0; e = -1.0; ff = -sy; }
        case 1: { a = -0.5; b = -0.866; c = -sx; d = -0.866; e = 0.50; ff = -sy; }
        case 2: { a = -0.5; b = 0.866; c = -sx; d = 0.866; e = 0.50; ff = -sy; }
        case 3: { a = 1.0; b = 0.0; c = sx; d = 0.0; e = -1.0; ff = sy; }
        case 4: { a = -0.5; b = -0.866; c = sx; d = -0.866; e = 0.50; ff = sy; }
        default: { a = -0.5; b = 0.866; c = sx; d = 0.866; e = 0.50; ff = sy; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec3<f32>(ox, oy, p.z);
}
"#,
};

pub static SYM_NG14: VariationDef = VariationDef {
    name: "sym_ng14",
    aliases: &[],
    display_name: "Sym NG14",
    category: VariationCategory::Plugin,
    phase: VariationPhase::Any,
    features: &[Feature::NeedsRng],
    parameters: &[
        param!("radius", "radius", unlimited_float, 0.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG14)."),
        param!("stepx", "stepx", unlimited_float, 0.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG14)."),
        param!("stepy", "stepy", unlimited_float, 0.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG14)."),
    ],
    init_param_count: 0,
    wgsl_init: None,
    state_count: 0,
    wgsl_state_init: None,
    wgsl_2d: r#"
fn variation_sym_ng14(p: vec2<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec2<f32> {
    let radius = get_param(xform_id, variation_id, 0u);
    let stepx = get_param(xform_id, variation_id, 1u);
    let stepy = get_param(xform_id, variation_id, 2u);
    let sx = stepx/2.0;
    let sy = stepy/2.0;
    let spacex = sqrt(radius*radius/2.0);
    let spacey = spacex;
    let zx = p.x + (spacex);
    let zy = p.y + (spacex);
    let idx = i32(floor(rng_nextf(rng) * 12.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 1.0; b = 0.0; c = -sx; d = 0.0; e = 1.0; ff = -sy; }
        case 1: { a = 1.0; b = 0.0; c = -sx; d = 0.0; e = -1.0; ff = -sy; }
        case 2: { a = -0.5; b = -0.866; c = -sx; d = 0.866; e = -0.50; ff = -sy; }
        case 3: { a = -0.5; b = 0.866; c = -sx; d = -0.866; e = -0.50; ff = -sy; }
        case 4: { a = -0.5; b = -0.866; c = -sx; d = -0.866; e = 0.50; ff = -sy; }
        case 5: { a = -0.5; b = 0.866; c = -sx; d = 0.866; e = 0.50; ff = -sy; }
        case 6: { a = 1.0; b = 0.0; c = sx; d = 0.0; e = 1.0; ff = sy; }
        case 7: { a = 1.0; b = 0.0; c = sx; d = 0.0; e = -1.0; ff = sy; }
        case 8: { a = -0.5; b = -0.866; c = sx; d = 0.866; e = -0.50; ff = sy; }
        case 9: { a = -0.5; b = 0.866; c = sx; d = -0.866; e = -0.50; ff = sy; }
        case 10: { a = -0.5; b = -0.866; c = sx; d = -0.866; e = 0.50; ff = sy; }
        default: { a = -0.5; b = 0.866; c = sx; d = 0.866; e = 0.50; ff = sy; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec2<f32>(ox, oy);
}
"#,
    wgsl_3d: r#"
fn variation_sym_ng14(p: vec3<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec3<f32> {
    let radius = get_param(xform_id, variation_id, 0u);
    let stepx = get_param(xform_id, variation_id, 1u);
    let stepy = get_param(xform_id, variation_id, 2u);
    let sx = stepx/2.0;
    let sy = stepy/2.0;
    let spacex = sqrt(radius*radius/2.0);
    let spacey = spacex;
    let zx = p.x + (spacex);
    let zy = p.y + (spacex);
    let idx = i32(floor(rng_nextf(rng) * 12.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 1.0; b = 0.0; c = -sx; d = 0.0; e = 1.0; ff = -sy; }
        case 1: { a = 1.0; b = 0.0; c = -sx; d = 0.0; e = -1.0; ff = -sy; }
        case 2: { a = -0.5; b = -0.866; c = -sx; d = 0.866; e = -0.50; ff = -sy; }
        case 3: { a = -0.5; b = 0.866; c = -sx; d = -0.866; e = -0.50; ff = -sy; }
        case 4: { a = -0.5; b = -0.866; c = -sx; d = -0.866; e = 0.50; ff = -sy; }
        case 5: { a = -0.5; b = 0.866; c = -sx; d = 0.866; e = 0.50; ff = -sy; }
        case 6: { a = 1.0; b = 0.0; c = sx; d = 0.0; e = 1.0; ff = sy; }
        case 7: { a = 1.0; b = 0.0; c = sx; d = 0.0; e = -1.0; ff = sy; }
        case 8: { a = -0.5; b = -0.866; c = sx; d = 0.866; e = -0.50; ff = sy; }
        case 9: { a = -0.5; b = 0.866; c = sx; d = -0.866; e = -0.50; ff = sy; }
        case 10: { a = -0.5; b = -0.866; c = sx; d = -0.866; e = 0.50; ff = sy; }
        default: { a = -0.5; b = 0.866; c = sx; d = 0.866; e = 0.50; ff = sy; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec3<f32>(ox, oy, p.z);
}
"#,
};

pub static SYM_NG15: VariationDef = VariationDef {
    name: "sym_ng15",
    aliases: &[],
    display_name: "Sym NG15",
    category: VariationCategory::Plugin,
    phase: VariationPhase::Any,
    features: &[Feature::NeedsRng],
    parameters: &[
        param!("radius", "radius", unlimited_float, 0.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG15)."),
        param!("stepx", "stepx", unlimited_float, 0.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG15)."),
        param!("stepy", "stepy", unlimited_float, 0.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG15)."),
    ],
    init_param_count: 0,
    wgsl_init: None,
    state_count: 0,
    wgsl_state_init: None,
    wgsl_2d: r#"
fn variation_sym_ng15(p: vec2<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec2<f32> {
    let radius = get_param(xform_id, variation_id, 0u);
    let stepx = get_param(xform_id, variation_id, 1u);
    let stepy = get_param(xform_id, variation_id, 2u);
    let sx = stepx/2.0;
    let sy = stepy/2.0;
    let spacex = sqrt(radius*radius/2.0);
    let spacey = spacex;
    let zx = p.x + (spacex);
    let zy = p.y + (spacex);
    let idx = i32(floor(rng_nextf(rng) * 12.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 0.0; b = 1.0; c = -sx; d = -1.00; e = 0.000; ff = -sy; }
        case 1: { a = 0.0; b = -1.0; c = -sx; d = -1.00; e = 0.000; ff = -sy; }
        case 2: { a = 0.866; b = -0.50; c = -sx; d = 0.50; e = 0.866; ff = -sy; }
        case 3: { a = 0.866; b = 0.50; c = -sx; d = 0.50; e = -0.866; ff = -sy; }
        case 4: { a = -0.866; b = -0.50; c = -sx; d = 0.50; e = -0.866; ff = -sy; }
        case 5: { a = -0.866; b = 0.50; c = -sx; d = 0.50; e = 0.866; ff = -sy; }
        case 6: { a = 0.0; b = 1.0; c = sx; d = -1.00; e = 0.000; ff = sy; }
        case 7: { a = 0.0; b = -1.0; c = sx; d = -1.00; e = 0.000; ff = sy; }
        case 8: { a = 0.866; b = -0.50; c = sx; d = 0.50; e = 0.866; ff = sy; }
        case 9: { a = 0.866; b = 0.50; c = sx; d = 0.50; e = -0.866; ff = sy; }
        case 10: { a = -0.866; b = -0.50; c = sx; d = 0.50; e = -0.866; ff = sy; }
        default: { a = -0.866; b = 0.50; c = sx; d = 0.50; e = 0.866; ff = sy; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec2<f32>(ox, oy);
}
"#,
    wgsl_3d: r#"
fn variation_sym_ng15(p: vec3<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec3<f32> {
    let radius = get_param(xform_id, variation_id, 0u);
    let stepx = get_param(xform_id, variation_id, 1u);
    let stepy = get_param(xform_id, variation_id, 2u);
    let sx = stepx/2.0;
    let sy = stepy/2.0;
    let spacex = sqrt(radius*radius/2.0);
    let spacey = spacex;
    let zx = p.x + (spacex);
    let zy = p.y + (spacex);
    let idx = i32(floor(rng_nextf(rng) * 12.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 0.0; b = 1.0; c = -sx; d = -1.00; e = 0.000; ff = -sy; }
        case 1: { a = 0.0; b = -1.0; c = -sx; d = -1.00; e = 0.000; ff = -sy; }
        case 2: { a = 0.866; b = -0.50; c = -sx; d = 0.50; e = 0.866; ff = -sy; }
        case 3: { a = 0.866; b = 0.50; c = -sx; d = 0.50; e = -0.866; ff = -sy; }
        case 4: { a = -0.866; b = -0.50; c = -sx; d = 0.50; e = -0.866; ff = -sy; }
        case 5: { a = -0.866; b = 0.50; c = -sx; d = 0.50; e = 0.866; ff = -sy; }
        case 6: { a = 0.0; b = 1.0; c = sx; d = -1.00; e = 0.000; ff = sy; }
        case 7: { a = 0.0; b = -1.0; c = sx; d = -1.00; e = 0.000; ff = sy; }
        case 8: { a = 0.866; b = -0.50; c = sx; d = 0.50; e = 0.866; ff = sy; }
        case 9: { a = 0.866; b = 0.50; c = sx; d = 0.50; e = -0.866; ff = sy; }
        case 10: { a = -0.866; b = -0.50; c = sx; d = 0.50; e = -0.866; ff = sy; }
        default: { a = -0.866; b = 0.50; c = sx; d = 0.50; e = 0.866; ff = sy; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec3<f32>(ox, oy, p.z);
}
"#,
};

pub static SYM_NG16: VariationDef = VariationDef {
    name: "sym_ng16",
    aliases: &[],
    display_name: "Sym NG16",
    category: VariationCategory::Plugin,
    phase: VariationPhase::Any,
    features: &[Feature::NeedsRng],
    parameters: &[
        param!("radius", "radius", unlimited_float, 0.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG16)."),
        param!("stepx", "stepx", unlimited_float, 0.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG16)."),
        param!("stepy", "stepy", unlimited_float, 0.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG16)."),
    ],
    init_param_count: 0,
    wgsl_init: None,
    state_count: 0,
    wgsl_state_init: None,
    wgsl_2d: r#"
fn variation_sym_ng16(p: vec2<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec2<f32> {
    let radius = get_param(xform_id, variation_id, 0u);
    let stepx = get_param(xform_id, variation_id, 1u);
    let stepy = get_param(xform_id, variation_id, 2u);
    let space = sqrt(radius*radius/2.0);
    let sx = stepx/2.0;
    let sy = stepy/2.0;
    let zx = p.x + (space);
    let zy = p.y + (space);
    let idx = i32(floor(rng_nextf(rng) * 12.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 1.0; b = 0.0; c = -sx; d = 0.0; e = 1.0; ff = -sy; }
        case 1: { a = 0.5; b = -0.866; c = -sx; d = 0.866; e = 0.5; ff = -sy; }
        case 2: { a = -0.5; b = -0.866; c = -sx; d = 0.866; e = -0.50; ff = -sy; }
        case 3: { a = -1.0; b = 0.000; c = -sx; d = 0.000; e = -1.00; ff = -sy; }
        case 4: { a = -0.5; b = 0.866; c = -sx; d = -0.866; e = -0.50; ff = -sy; }
        case 5: { a = 0.5; b = 0.866; c = -sx; d = -0.866; e = 0.50; ff = -sy; }
        case 6: { a = 1.0; b = 0.0; c = sx; d = 0.0; e = 1.0; ff = sy; }
        case 7: { a = 0.5; b = -0.866; c = sx; d = 0.866; e = 0.5; ff = sy; }
        case 8: { a = -0.5; b = -0.866; c = sx; d = 0.866; e = -0.50; ff = sy; }
        case 9: { a = -1.0; b = 0.000; c = sx; d = 0.000; e = -1.00; ff = sy; }
        case 10: { a = -0.5; b = 0.866; c = sx; d = -0.866; e = -0.50; ff = sy; }
        default: { a = 0.5; b = 0.866; c = sx; d = -0.866; e = 0.50; ff = sy; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec2<f32>(ox, oy);
}
"#,
    wgsl_3d: r#"
fn variation_sym_ng16(p: vec3<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec3<f32> {
    let radius = get_param(xform_id, variation_id, 0u);
    let stepx = get_param(xform_id, variation_id, 1u);
    let stepy = get_param(xform_id, variation_id, 2u);
    let space = sqrt(radius*radius/2.0);
    let sx = stepx/2.0;
    let sy = stepy/2.0;
    let zx = p.x + (space);
    let zy = p.y + (space);
    let idx = i32(floor(rng_nextf(rng) * 12.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 1.0; b = 0.0; c = -sx; d = 0.0; e = 1.0; ff = -sy; }
        case 1: { a = 0.5; b = -0.866; c = -sx; d = 0.866; e = 0.5; ff = -sy; }
        case 2: { a = -0.5; b = -0.866; c = -sx; d = 0.866; e = -0.50; ff = -sy; }
        case 3: { a = -1.0; b = 0.000; c = -sx; d = 0.000; e = -1.00; ff = -sy; }
        case 4: { a = -0.5; b = 0.866; c = -sx; d = -0.866; e = -0.50; ff = -sy; }
        case 5: { a = 0.5; b = 0.866; c = -sx; d = -0.866; e = 0.50; ff = -sy; }
        case 6: { a = 1.0; b = 0.0; c = sx; d = 0.0; e = 1.0; ff = sy; }
        case 7: { a = 0.5; b = -0.866; c = sx; d = 0.866; e = 0.5; ff = sy; }
        case 8: { a = -0.5; b = -0.866; c = sx; d = 0.866; e = -0.50; ff = sy; }
        case 9: { a = -1.0; b = 0.000; c = sx; d = 0.000; e = -1.00; ff = sy; }
        case 10: { a = -0.5; b = 0.866; c = sx; d = -0.866; e = -0.50; ff = sy; }
        default: { a = 0.5; b = 0.866; c = sx; d = -0.866; e = 0.50; ff = sy; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec3<f32>(ox, oy, p.z);
}
"#,
};

pub static SYM_NG17: VariationDef = VariationDef {
    name: "sym_ng17",
    aliases: &[],
    display_name: "Sym NG17",
    category: VariationCategory::Plugin,
    phase: VariationPhase::Any,
    features: &[Feature::NeedsRng],
    parameters: &[
        param!("radius", "radius", unlimited_float, 0.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG17)."),
        param!("stepx", "stepx", unlimited_float, 0.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG17)."),
        param!("stepy", "stepy", unlimited_float, 0.0, -100.0, 100.0, "Network-symmetry parameter (see JWildfire SymNetG17)."),
    ],
    init_param_count: 0,
    wgsl_init: None,
    state_count: 0,
    wgsl_state_init: None,
    wgsl_2d: r#"
fn variation_sym_ng17(p: vec2<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec2<f32> {
    let radius = get_param(xform_id, variation_id, 0u);
    let stepx = get_param(xform_id, variation_id, 1u);
    let stepy = get_param(xform_id, variation_id, 2u);
    let space = sqrt(radius*radius/2.0);
    let sx = stepx/2.0;
    let sy = stepy/2.0;
    let zx = p.x + (space);
    let zy = p.y + (space);
    let idx = i32(floor(rng_nextf(rng) * 24.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 1.0; b = 0.0; c = -sx; d = 0.0; e = 1.0; ff = -sy; }
        case 1: { a = 1.0; b = 0.0; c = -sx; d = 0.0; e = -1.0; ff = -sy; }
        case 2: { a = 0.5; b = -0.866; c = -sx; d = 0.866; e = 0.50; ff = -sy; }
        case 3: { a = 0.5; b = 0.866; c = -sx; d = 0.866; e = -0.50; ff = -sy; }
        case 4: { a = -0.5; b = -0.866; c = -sx; d = 0.866; e = -0.50; ff = -sy; }
        case 5: { a = -0.5; b = 0.866; c = -sx; d = 0.866; e = 0.50; ff = -sy; }
        case 6: { a = -1.0; b = 0.000; c = -sx; d = 0.000; e = -1.00; ff = -sy; }
        case 7: { a = -1.0; b = 0.000; c = -sx; d = 0.000; e = 1.00; ff = -sy; }
        case 8: { a = -0.5; b = 0.866; c = -sx; d = -0.866; e = -0.50; ff = -sy; }
        case 9: { a = -0.5; b = -0.866; c = -sx; d = -0.866; e = 0.50; ff = -sy; }
        case 10: { a = 0.5; b = 0.866; c = -sx; d = -0.866; e = 0.50; ff = -sy; }
        case 11: { a = 0.5; b = -0.866; c = -sx; d = -0.866; e = -0.50; ff = -sy; }
        case 12: { a = 1.0; b = 0.0; c = sx; d = 0.0; e = 1.0; ff = sy; }
        case 13: { a = 1.0; b = 0.0; c = sx; d = 0.0; e = -1.0; ff = sy; }
        case 14: { a = 0.5; b = -0.866; c = sx; d = 0.866; e = 0.50; ff = sy; }
        case 15: { a = 0.5; b = 0.866; c = sx; d = 0.866; e = -0.50; ff = sy; }
        case 16: { a = -0.5; b = -0.866; c = sx; d = 0.866; e = -0.50; ff = sy; }
        case 17: { a = -0.5; b = 0.866; c = sx; d = 0.866; e = 0.50; ff = sy; }
        case 18: { a = -1.0; b = 0.000; c = sx; d = 0.000; e = -1.00; ff = sy; }
        case 19: { a = -1.0; b = 0.000; c = sx; d = 0.000; e = 1.00; ff = sy; }
        case 20: { a = -0.5; b = 0.866; c = sx; d = -0.866; e = -0.50; ff = sy; }
        case 21: { a = -0.5; b = -0.866; c = sx; d = -0.866; e = 0.50; ff = sy; }
        case 22: { a = 0.5; b = 0.866; c = sx; d = -0.866; e = 0.50; ff = sy; }
        default: { a = 0.5; b = -0.866; c = sx; d = -0.866; e = -0.50; ff = sy; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec2<f32>(ox, oy);
}
"#,
    wgsl_3d: r#"
fn variation_sym_ng17(p: vec3<f32>, xform_id: u32, variation_id: u32, rng: ptr<function, RngState>) -> vec3<f32> {
    let radius = get_param(xform_id, variation_id, 0u);
    let stepx = get_param(xform_id, variation_id, 1u);
    let stepy = get_param(xform_id, variation_id, 2u);
    let space = sqrt(radius*radius/2.0);
    let sx = stepx/2.0;
    let sy = stepy/2.0;
    let zx = p.x + (space);
    let zy = p.y + (space);
    let idx = i32(floor(rng_nextf(rng) * 24.0));
    var a: f32; var b: f32; var c: f32; var d: f32; var e: f32; var ff: f32;
    switch (idx) {
        case 0: { a = 1.0; b = 0.0; c = -sx; d = 0.0; e = 1.0; ff = -sy; }
        case 1: { a = 1.0; b = 0.0; c = -sx; d = 0.0; e = -1.0; ff = -sy; }
        case 2: { a = 0.5; b = -0.866; c = -sx; d = 0.866; e = 0.50; ff = -sy; }
        case 3: { a = 0.5; b = 0.866; c = -sx; d = 0.866; e = -0.50; ff = -sy; }
        case 4: { a = -0.5; b = -0.866; c = -sx; d = 0.866; e = -0.50; ff = -sy; }
        case 5: { a = -0.5; b = 0.866; c = -sx; d = 0.866; e = 0.50; ff = -sy; }
        case 6: { a = -1.0; b = 0.000; c = -sx; d = 0.000; e = -1.00; ff = -sy; }
        case 7: { a = -1.0; b = 0.000; c = -sx; d = 0.000; e = 1.00; ff = -sy; }
        case 8: { a = -0.5; b = 0.866; c = -sx; d = -0.866; e = -0.50; ff = -sy; }
        case 9: { a = -0.5; b = -0.866; c = -sx; d = -0.866; e = 0.50; ff = -sy; }
        case 10: { a = 0.5; b = 0.866; c = -sx; d = -0.866; e = 0.50; ff = -sy; }
        case 11: { a = 0.5; b = -0.866; c = -sx; d = -0.866; e = -0.50; ff = -sy; }
        case 12: { a = 1.0; b = 0.0; c = sx; d = 0.0; e = 1.0; ff = sy; }
        case 13: { a = 1.0; b = 0.0; c = sx; d = 0.0; e = -1.0; ff = sy; }
        case 14: { a = 0.5; b = -0.866; c = sx; d = 0.866; e = 0.50; ff = sy; }
        case 15: { a = 0.5; b = 0.866; c = sx; d = 0.866; e = -0.50; ff = sy; }
        case 16: { a = -0.5; b = -0.866; c = sx; d = 0.866; e = -0.50; ff = sy; }
        case 17: { a = -0.5; b = 0.866; c = sx; d = 0.866; e = 0.50; ff = sy; }
        case 18: { a = -1.0; b = 0.000; c = sx; d = 0.000; e = -1.00; ff = sy; }
        case 19: { a = -1.0; b = 0.000; c = sx; d = 0.000; e = 1.00; ff = sy; }
        case 20: { a = -0.5; b = 0.866; c = sx; d = -0.866; e = -0.50; ff = sy; }
        case 21: { a = -0.5; b = -0.866; c = sx; d = -0.866; e = 0.50; ff = sy; }
        case 22: { a = 0.5; b = 0.866; c = sx; d = -0.866; e = 0.50; ff = sy; }
        default: { a = 0.5; b = -0.866; c = sx; d = -0.866; e = -0.50; ff = sy; }
    }
    let ox = a * zx + b * zy + c;
    let oy = d * zx + e * zy + ff;
    return vec3<f32>(ox, oy, p.z);
}
"#,
};
