"""Apply doc-comments + per-param descriptions to macmillan_misc.rs and harmonograph_misc.rs.

One-off script for the variations-bulk-metadata project. Idempotent.

Note: macmillan has no attribution — left without `# Authors` block per the
unknown-author convention. Tracked in VARIATIONS_TODOS.md."""
import re
import textwrap

DOC = {
    "MACMILLAN": (
        "macmillan_misc.rs",
        "Self-iterating McMillan-map walker. The McMillan map is the discrete dynamical system `y' = -x + 2a · y/(1+y²) + b·y` (from Edwin McMillan's 1971 nonlinear-dynamics work); each iteration applies the 2nd-order form twice from a per-thread state `(xa, x, y)` initialized to `(startx, startx, starty)`. Ignores the input position and emits the post-iteration `(x, y)` as a deterministic trajectory; also writes a color register `vc` derived from the running accumulator plus this iteration's own contribution. First port to exercise the full feature set (`needs_accum + needs_transform + writes_color + wgsl_state_init`).",
        None,  # Unknown author — see VARIATIONS_TODOS.md
    ),
    "HARMONOGRAPH_JS": (
        "harmonograph_misc.rs",
        "Damped-pendulum harmonograph — emits points on a Lissajous-like curve generated by 4 damped sinusoids (2 per axis) sampled at a random `t ∈ [0, time]`. Each axis's value is `a₁·sin(t·f₁ + p₁°)·e^(-d₁·t) + a₂·sin(t·f₂ + p₂°)·e^(-d₂·t)`, scaled by `1/180`. The Y-axis oscillators additionally get a `+90°` phase shift on their `p` params to break the X/Y symmetry. Upstream cpp has a porter bug — the `mo()` helper references `VAR(a1)` globals instead of its local args; the Java original (embedded as comments in the cpp source) uses locals correctly, and we follow Java.",
        ["Jesus Sosa"],
    ),
}

PARAM_DOC = {
    # macmillan
    ("MACMILLAN", "a"): "McMillan-map parameter `a` — coefficient of the nonlinear term `2a · y/(1+y²)`. The classic chaotic regime is around `a ≈ 1.6`.",
    ("MACMILLAN", "b"): "McMillan-map parameter `b` — linear coefficient on `y`. Together with `a` determines whether the trajectory is bounded, periodic, or chaotic.",
    ("MACMILLAN", "N"): "Declared but unused in the body — the map is hardcoded to two iterations per call. Possibly a port omission (upstream cpp may use `N` as an inner-loop bound). Tracked in TODO.",
    ("MACMILLAN", "startx"): "Initial X coordinate for the per-thread state (read once via `wgsl_state_init` at thread start). Sets both `xa` and `x` slots.",
    ("MACMILLAN", "starty"): "Initial Y coordinate for the per-thread state.",

    # harmonograph_js
    ("HARMONOGRAPH_JS", "seed"): "Declared but unused in this port — upstream cpp re-seeds `GOODRAND` per Prepare; we use the per-thread RNG instead. Kept in the parameter list for cpp/Java interface parity.",
    ("HARMONOGRAPH_JS", "time"): "Maximum value of the random sampling time `t ∈ [0, time]`. Larger values let the damped exponential `e^(-d·t)` decay further, attenuating contributions from later samples.",

    ("HARMONOGRAPH_JS", "a1"): "X-axis oscillator 1: amplitude. Builds `a1·sin(t·f1 + p1°)·e^(-d1·t)` — one of two terms summed to make the X output. Declared `int` to match the upstream parameter type.",
    ("HARMONOGRAPH_JS", "f1"): "X-axis oscillator 1: frequency.",
    ("HARMONOGRAPH_JS", "p1"): "X-axis oscillator 1: phase offset in degrees (converted to radians internally).",
    ("HARMONOGRAPH_JS", "d1"): "X-axis oscillator 1: exponential damping rate (0 = no damping; larger values attenuate later samples faster).",

    ("HARMONOGRAPH_JS", "a2"): "X-axis oscillator 2: amplitude. Second term of the X-axis sum.",
    ("HARMONOGRAPH_JS", "f2"): "X-axis oscillator 2: frequency.",
    ("HARMONOGRAPH_JS", "p2"): "X-axis oscillator 2: phase offset in degrees.",
    ("HARMONOGRAPH_JS", "d2"): "X-axis oscillator 2: exponential damping rate.",

    ("HARMONOGRAPH_JS", "a3"): "Y-axis oscillator 1: amplitude. Builds `a3·sin(t·f3 + (p3+90)°)·e^(-d3·t)` — first term of the Y-axis sum, with an extra `+90°` phase shift.",
    ("HARMONOGRAPH_JS", "f3"): "Y-axis oscillator 1: frequency.",
    ("HARMONOGRAPH_JS", "p3"): "Y-axis oscillator 1: phase offset in degrees. The body adds `+90°` before the `π/180` conversion.",
    ("HARMONOGRAPH_JS", "d3"): "Y-axis oscillator 1: exponential damping rate.",

    ("HARMONOGRAPH_JS", "a4"): "Y-axis oscillator 2: amplitude. Second term of the Y-axis sum (also gets the `+90°` phase shift on `p4`).",
    ("HARMONOGRAPH_JS", "f4"): "Y-axis oscillator 2: frequency.",
    ("HARMONOGRAPH_JS", "p4"): "Y-axis oscillator 2: phase offset in degrees (with `+90°` shift).",
    ("HARMONOGRAPH_JS", "d4"): "Y-axis oscillator 2: exponential damping rate.",
}


def find_macro_close(text: str, open_paren_idx: int) -> int:
    assert text[open_paren_idx] == "("
    depth = 1
    i = open_paren_idx + 1
    n = len(text)
    while i < n:
        c = text[i]
        if c == '"':
            i += 1
            while i < n:
                if text[i] == "\\":
                    i += 2
                    continue
                if text[i] == '"':
                    i += 1
                    break
                i += 1
            continue
        if c == "(":
            depth += 1
        elif c == ")":
            depth -= 1
            if depth == 0:
                return i
        i += 1
    return -1


files = {}
for static_name, (path_rel, body, authors) in DOC.items():
    files.setdefault(path_rel, {})[static_name] = (body, authors)

for path_rel, doc_map in files.items():
    full_path = f"src/variations/defs/{path_rel}"
    with open(full_path, "rb") as f:
        src = f.read().decode("utf-8")

    inserted = 0
    already = 0
    for name, (body, authors) in doc_map.items():
        target = f"\npub static {name}: VariationDef = VariationDef {{"
        if target not in src:
            print(f"  WARN: no match for {name} in {path_rel}")
            continue
        idx = src.find(target)
        prefix = src[:idx]
        last_nl = prefix.rfind("\n")
        if last_nl != -1:
            prev_line = src[last_nl + 1:idx + 1].strip()
            if prev_line.startswith("///"):
                already += 1
                continue
        lines = []
        for paragraph in body.split("\n"):
            wrapped = textwrap.fill(paragraph, width=72) if paragraph.strip() else ""
            for line in wrapped.split("\n"):
                lines.append(f"/// {line}".rstrip())
        if authors:
            lines.append("///")
            lines.append("/// # Authors")
            for author in authors:
                lines.append(f"/// - {author}")
        doc = "\n".join(lines)
        src = src.replace(target, f"\n{doc}\npub static {name}: VariationDef = VariationDef {{", 1)
        inserted += 1
    print(f"  {path_rel} pass1: inserted {inserted}, already {already}")

    pinserted = 0
    palready = 0
    for (static_name, param_name), desc in PARAM_DOC.items():
        if static_name not in doc_map:
            continue
        start_pattern = f"pub static {static_name}: VariationDef"
        start_idx = src.find(start_pattern)
        if start_idx == -1:
            continue
        next_static = src.find("\npub static ", start_idx + 1)
        end_idx = next_static if next_static != -1 else len(src)
        block = src[start_idx:end_idx]

        head = f'param!("{param_name}"'
        head_idx = block.find(head)
        if head_idx == -1:
            print(f"  WARN: no param {static_name}.{param_name}")
            continue
        open_idx = block.find("(", head_idx)
        close_idx = find_macro_close(block, open_idx)
        if close_idx == -1:
            print(f"  WARN: unbalanced param {static_name}.{param_name}")
            continue
        inner = block[open_idx + 1:close_idx]
        depth = 0
        in_str = False
        commas = 0
        j = 0
        while j < len(inner):
            ch = inner[j]
            if in_str:
                if ch == "\\":
                    j += 2
                    continue
                if ch == '"':
                    in_str = False
            else:
                if ch == '"':
                    in_str = True
                elif ch == "(":
                    depth += 1
                elif ch == ")":
                    depth -= 1
                elif ch == "," and depth == 0:
                    commas += 1
            j += 1
        if commas >= 6:
            palready += 1
            continue

        new_block = (
            block[:close_idx]
            + f', "{desc}"'
            + block[close_idx:]
        )
        src = src[:start_idx] + new_block + src[end_idx:]
        pinserted += 1
    print(f"  {path_rel} pass2: injected {pinserted}, already {palready}")

    with open(full_path, "wb") as f:
        f.write(src.encode("utf-8"))
